export const ACTION_LABELS = {
  save: "حفظ",
  lock: "إقفال",
  view: "رؤية",
  add: "إضافة",
  edit: "تعديل",
  delete: "حذف",
  print: "طباعة",
  send: "إرسال",
  void: "إلغاء",
  hold: "تعليق",
  discount: "خصم",
  profit: "ربح",
  manage_permissions: "إدارة الصلاحيات",
  edit_general: "تعديل الإعدادات العامة",
  edit_security: "تعديل إعدادات الأمان",
  studio: "استوديو الطباعة",
  calibrate: "معايرة الطابعة",
  device_profile: "ملف جهاز الطابعة",
  adjust: "تسوية",
  transfer: "تحويل",
  export: "تصدير",
  create: "إنشاء",
  restore: "استعادة",
  import_undo: "التراجع عن الاستيراد",
  edit_tax_rate: "تعديل نسبة الضريبة",
  view_sensitive: "رؤية البيانات المالية الحساسة",
  backdate_records: "تعديل التواريخ السابقة",
  salary_view: "عرض الراتب",
  salary_edit: "تعديل الراتب",
  manage_advances: "إدارة السلف",
  manage_deductions: "إدارة الخصومات",
  manage_bonuses: "إدارة المكافئات",
  settle_payroll: "صرف الرواتب",
  manage_templates: "إدارة القوالب",
  connect: "ربط/فصل القنوات",
  manage_events: "إدارة أحداث التتبع",
  pull: "سحب بيانات من المتجر",
  push: "دفع البيانات إلى المتجر",
  configure: "إعداد المزامنة",
};

export const ACTION_DESCRIPTIONS = {
  save: "حفظ نسخة من بيانات الفترة الحالية",
  lock: "إقفال النسخة ومنع تعديلها لاحقا",
  view: "مشاهدة وعرض محتوى الصفحة والبيانات",
  add: "إضافة سجلات وبيانات جديدة",
  edit: "تعديل وتحديث السجلات والبيانات الموجودة",
  delete: "حذف السجلات والبيانات نهائياً",
  print: "طباعة التقارير والفواتير والمستندات",
  send: "إرسال مستند أو رسالة إلى جهة اتصال عبر واتساب أو غيره",
  void: "إلغاء الفواتير والمعاملات المالية",
  hold: "تعليق الفاتورة مؤقتاً لاستكمالها لاحقاً",
  discount: "منح خصومات على فواتير البيع",
  profit: "عرض تحليل ربح الفاتورة الحالية",
  manage_permissions: "تعديل صلاحيات المستخدمين الآخرين",
  edit_general: "تعديل الإعدادات العامة للنظام",
  edit_security: "تعديل إعدادات الأمان والحماية",
  studio: "فتح استوديو تصميم قوالب الطباعة وتعديل التصميم",
  calibrate: "معايرة وضبط حجم الورق والهوامش للطابعة",
  device_profile: "استيراد وتصدير ملف إعدادات جهاز الطابعة",
  adjust: "إجراء تسويات يدوية على المخزون",
  transfer: "تحويل الأصناف بين المخازن والفروع",
  export: "تصدير البيانات والتقارير إلى ملفات خارجية",
  create: "إنشاء نسخ احتياطية جديدة",
  restore: "استعادة النظام من نسخة احتياطية",
  import_undo: "التراجع عن عملية استيراد الأصناف خلال 24 ساعة",
  edit_tax_rate: "تعديل نسبة الضريبة على الفواتير",
  view_sensitive: "مشاهدة البيانات المالية الحساسة (الأرباح، الهوامش، التكاليف)",
  backdate_records: "إضافة أو تعديل أو حذف سجلات بتواريخ أيام سابقة",
  salary_view: "مشاهدة بيانات الراتب",
  salary_edit: "تعديل الراتب وفترة الدفع",
  manage_advances: "إدارة السلفيات (إضافة، تعديل، حذف)",
  manage_deductions: "إدارة الخصومات",
  manage_bonuses: "إدارة المكافئات",
  settle_payroll: "صرف الرواتب وإنشاء مصروفات",
  manage_templates: "إدارة القوالب (إنشاء، تعديل، حذف، تفعيل)",
  connect: "ربط وفصل قنوات التواصل (واتساب، تيليجرام، SMS، البريد)",
  manage_events: "تعديل الأحداث المراد متابعتها على تيليجرام",
  pull: "سحب المنتجات والبيانات من المتجر الإلكتروني إلى النظام المحلي",
  push: "دفع التغييرات المحلية إلى المتجر الإلكتروني",
  configure: "إعداد بيانات الاتصال بالمتجر الإلكتروني وتفعيل المزامنة التلقائية",
};

export const PAGE_PERMISSIONS = {
  owner_statement: { label: 'تقرير صاحب المحل', actions: ['view', 'save', 'lock', 'print'] },
  pos: { label: 'نقطة البيع', actions: ['view', 'add', 'edit', 'delete', 'void', 'hold', 'discount', 'print', 'profit', 'edit_tax_rate'] },
  daily_treasury: { label: 'الخزينة اليومية', actions: ['view', 'add', 'edit', 'delete', 'print'] },
  analytics: { label: 'التحليلات والمبيعات', actions: ['view', 'export', 'view_sensitive'] },
  sales: { label: 'فواتير المبيعات', actions: ['view', 'add', 'edit', 'delete', 'print', 'void'] },
  purchases: { label: 'فواتير المشتريات', actions: ['view', 'add', 'edit', 'delete', 'print'] },
  purchase_orders: { label: 'طلبات التوريد', actions: ['view', 'add', 'edit', 'delete', 'print'] },
  purchase_returns: { label: 'مرتجع المشتريات', actions: ['view', 'add', 'edit', 'delete', 'print'] },
  sales_returns: { label: 'مرتجع المبيعات', actions: ['view', 'add', 'edit', 'delete', 'print'] },
  branch_transfer: { label: 'نقل المخزون', actions: ['view', 'add', 'edit', 'delete', 'print'] },
  quotations: { label: 'عرض سعر', actions: ['view', 'add', 'edit', 'delete', 'print'] },
  customer_accounts: { label: 'حسابات العملاء', actions: ['view', 'add', 'edit', 'delete', 'print'] },
  supplier_accounts: { label: 'حسابات الموردين', actions: ['view', 'add', 'edit', 'delete', 'print'] },
  revenues: { label: 'تسجيل الإيرادات', actions: ['view', 'add', 'edit', 'delete', 'print', 'backdate_records'] },
  expenses: { label: 'تسجيل المصروفات', actions: ['view', 'add', 'edit', 'delete', 'print', 'backdate_records'] },
  withdrawals: { label: 'تسجيل المسحوبات', actions: ['view', 'add', 'edit', 'delete', 'print', 'backdate_records'] },
  payment_methods: { label: 'وسائل الدفع', actions: ['view', 'add', 'edit', 'delete', 'print'] },
  cheques: { label: 'إدارة الشيكات', actions: ['view', 'add', 'edit', 'delete', 'print'] },
  items: { label: 'قاعدة الأصناف', actions: ['view', 'add', 'edit', 'delete', 'print', 'import_undo'] },
  categories: { label: 'أقسام الأصناف', actions: ['view', 'add', 'edit', 'delete', 'print'] },
  bulk_price_update: { label: 'تحديث الأسعار', actions: ['view', 'add', 'edit', 'delete', 'print'] },
  stock_transfer: { label: 'تحويل مخزني', actions: ['view', 'add', 'edit', 'delete', 'print'] },
  physical_count: { label: 'الجرد الفعلي', actions: ['view', 'add', 'edit', 'delete', 'print'] },
  promotions: { label: 'العروض والتخفيضات', actions: ['view', 'add', 'edit', 'delete', 'print'] },
  branches: { label: 'الفروع', actions: ['view', 'add', 'edit', 'delete', 'print'] },
  customers: { label: 'العملاء', actions: ['view', 'add', 'edit', 'delete', 'print'] },
  suppliers: { label: 'الموردين', actions: ['view', 'add', 'edit', 'delete', 'print'] },
  warehouses: { label: 'المخازن', actions: ['view', 'add', 'edit', 'delete', 'print'] },
  units: { label: 'وحدات القياس', actions: ['view', 'add', 'edit', 'delete', 'print'] },
  financial_categories: { label: 'أقسام الحركات المالية', actions: ['view', 'add', 'edit', 'delete', 'print'] },
  reports: { label: 'مركز التقارير', actions: ['view', 'export'] },
  users: { label: 'المستخدمين', actions: ['view', 'add', 'edit', 'delete', 'manage_permissions', 'print'] },
  employees: { label: 'الموظفين', actions: ['view', 'add', 'edit', 'delete', 'print', 'salary_view', 'salary_edit', 'manage_advances', 'manage_deductions', 'manage_bonuses', 'settle_payroll'] },
  settings: { label: 'الإعدادات العامة', actions: ['view', 'edit', 'edit_general', 'edit_security'] },
  print_settings: { label: 'إعدادات الطباعة', actions: ['view', 'edit', 'studio', 'calibrate', 'device_profile'] },
  dashboard: { label: 'لوحة التحكم', actions: ['view'] },
  stock: { label: 'المخزون', actions: ['view', 'add', 'edit', 'delete', 'adjust', 'transfer', 'print'] },
  payments: { label: 'المدفوعات', actions: ['view', 'add', 'edit', 'delete', 'print'] },
  notifications: { label: 'الإشعارات', actions: ['view', 'edit'] },
  employee_adjustments: { label: 'مكافآت وخصومات', actions: ['view', 'add'] },
  backup: { label: 'النسخ الاحتياطي', actions: ['view', 'create', 'restore', 'export', 'empty'] },
  updates: { label: 'التحديثات', actions: ['view'] },
  history: { label: 'سجل النشاط', actions: ['view', 'export'] },
  whatsapp_crm: { label: 'مركز الرسائل والحملات', actions: ['view', 'add', 'edit', 'delete', 'send', 'connect', 'manage_templates', 'manage_events'] },
  whatsapp_receipt: { label: 'إرسال إيصال واتساب', actions: ['view', 'send'] },
  sync: { label: 'المزامنة (E-Commerce)', actions: ['view', 'pull', 'push', 'configure', 'restore'] },
  restaurant_tables: { label: 'طاولات المطعم', actions: ['view', 'add', 'edit', 'delete'] },
  restaurant_modifiers: { label: 'إضافات المطعم (موديفير)', actions: ['view', 'add', 'edit', 'delete'] },
  gold_pricing: { label: 'تسعير الذهب', actions: ['view', 'add', 'edit', 'delete'] },
  repair_orders: { label: 'أوامر الصيانة', actions: ['view', 'add', 'edit', 'delete', 'print'] },
  serial_search: { label: 'بحث سيريال / IMEI', actions: ['view'] },
};

// Default permissions for new user role (POS only)
export const DEFAULT_USER_PERMISSIONS = {
  pos: ['view', 'add'],
  whatsapp_receipt: ['send'],
};

// Role permission presets
export const ROLE_PRESETS = {
  admin: null, // null means full access (handled by role check)
  user: DEFAULT_USER_PERMISSIONS,
};

// Ordered list of all unique actions across all pages (for matrix column headers)
const ALL_UNIQUE_ACTIONS = [...new Set(Object.values(PAGE_PERMISSIONS).flatMap(p => p.actions))];
const ACTION_ORDER = ['view', 'add', 'edit', 'delete', 'print', 'send', 'void', 'hold', 'discount', 'export', 'adjust', 'transfer', 'manage_permissions', 'edit_general', 'edit_security', 'studio', 'calibrate', 'device_profile', 'create', 'restore', 'import_undo', 'edit_tax_rate', 'view_sensitive', 'backdate_records', 'salary_view', 'salary_edit', 'manage_advances', 'manage_deductions', 'manage_bonuses', 'settle_payroll', 'manage_templates', 'connect', 'manage_events', 'pull', 'push', 'configure'];
export const ALL_ACTIONS = ACTION_ORDER.filter(a => ALL_UNIQUE_ACTIONS.includes(a));
