const REPORT_DESCRIPTIONS = {
  // ── تقارير العملاء ──
  "ar-aging": "يعرض توزيع الذمم المدينة على العملاء حسب فترات التقادم (0-30، 31-60، 61-90، +90 يوماً) مع إجمالي المستحق والمتأخر، لتحديد العملاء المتعثرة ذممهم ومتابعة التحصيل.",
  "top-customers": "يكشف عن أهم العملاء من حيث إجمالي المبيعات وصافيها مع هامش الربح ومتوسط الفاتورة، لتمكين استراتيجيات البيع والولاء للعملاء الأكثر ربحية.",
  "collection-efficiency": "يحلل كفاءة تحصيل المستحقات لكل عميل من خلال إجمالي الفواتير والمحصل والمستحق ونسبة التحصيل، لقياس أداء إدارة الائتمان والتنبؤ بالتدفق النقدي.",
  "customer-loyalty": "يقيس ولاء العملاء من خلال تواتر الشراء الشهري ومتوسط قيمة الفاتورة ونسبة الخصم والمرتجعات، لتحديد العملاء المخلصين ومنحهم أولوية في العروض والحوافز.",

  // ── تقارير الموردين ──
  "ap-aging": "يعرض توزيع الذمم الدائنة على الموردين حسب فترات التقادم (0-30، 31-60، 61-90، +90 يوماً) مع إجمالي المستحق، لإدارة السيولة النقدية وتحديد أولويات السداد.",
  "supplier-reliability": "يقيم موثوقية الموردين بناءً على نسبة المرتجعات ومتوسط أيام السداد وتشتت الأسعار وتكرار الطلبات، لاختيار الموردين الأفضل أداءً والأكثر استقراراً في التسعير.",
  "customer-balance-list": "يعرض جميع العملاء مع أرصدتهم الحالية (مديون أو دائن) مرتبة تنازلياً حسب قيمة الرصيد. يتم إخفاء العملاء ذوي الرصيد الصفري.",
  "supplier-balance-list": "يعرض جميع الموردين مع أرصدتهم الحالية (دائن أو مديون) مرتبة تنازلياً حسب قيمة الرصيد. يتم إخفاء الموردين ذوي الرصيد الصفري.",
};

const REPORT_TITLES = {
  "daily-sales": "الملخص اليومي للمبيعات",
  "detailed-sales": "المبيعات التفصيلية",
  "sales-by-item": "مبيعات حسب الصنف",
  "sales-by-category": "مبيعات حسب الفئة",
  "sales-by-cashier": "مبيعات حسب الكاشير",
  "sales-by-payment": "مبيعات حسب طريقة الدفع",
  "sales-heatmap": "خريطة كثافة المبيعات",
  "exceptions": "استثناءات المبيعات",
  "period-comparison": "مقارنة الفترات",
  "slow-moving": "الأصناف بطيئة الحركة",
  "stock-levels": "أرصدة المخزون",
  "stock-movements": "حركات المخزون",
  "stock-valuation": "تقييم المخزون",
  "count-sheet": "كشف الجرد",
  "reorder": "إعادة الطلب",
  "expiry": "تواريخ الصلاحية",
  "profit-loss": "الأرباح والخسائر",
  "cash-flow": "التدفق النقدي",
  "treasury": "الخزائن والبنوك",
  "vat": "ضريبة القيمة المضافة",
  "customer-statement": "كشف حساب عميل",
  "shift-history": "سجل الورديات",
  "audit-log": "سجل التدقيق",
  "gross-net-sales": "إجمالي وصافي المبيعات",
  "sales-returns": "مرتجعات المبيعات",
  "discount-analysis": "تحليل الخصومات",
  "margin-by-item": "هامش الربح حسب الصنف",
  "margin-by-category": "هامش الربح حسب الفئة",
  "purchase-summary": "ملخص المشتريات",
  "detailed-purchases": "المشتريات التفصيلية",
  "purchases-by-supplier": "مشتريات حسب المورد",
  "purchases-by-item": "مشتريات حسب الصنف",
  "purchase-returns": "مرتجعات المشتريات",
  "supplier-pricing": "أسعار الموردين",
  "inventory-aging": "أعمار المخزون",
  "dead-stock": "المخزون الراكد",
  "supplier-statement": "كشف حساب مورد",
  "cash-consistency": "مطابقة النقدية",
  "payment-method-flow": "تدفق وسائل الدفع",
  "bank-cash-split": "توزيع الخزائن والبنوك",
  "reconciliation-exceptions": "استثناءات التسوية",
  "output-vat": "ضريبة المخرجات",
  "input-vat": "ضريبة المدخلات",
  "vat-filing-summary": "ملخص الإقرار الضريبي",
  "returns-tax-effect": "الأثر الضريبي للمرتجعات",
  "user-activity": "نشاط المستخدمين",
  "margin-health": "صحة هوامش الربح",
  "sales-returns-summary": "ملخص مرتجعات المبيعات",
  "sales-returns-by-customer": "مرتجعات المبيعات حسب العميل",
  "purchase-returns-summary": "ملخص مرتجعات المشتريات",
  "purchase-returns-by-supplier": "مرتجعات المشتريات حسب المورد",
  "daily-sessions": "جلسات الخزينة اليومية",
  "withdrawals-report": "تقرير السحوبات",
  "expense-summary": "ملخص المصروفات",
  "detailed-expenses": "المصروفات التفصيلية",
  "expenses-by-category": "المصروفات حسب الفئة",
  "expenses-by-payment": "المصروفات حسب طريقة الدفع",
  "revenue-summary": "ملخص الإيرادات",
  "detailed-revenues": "الإيرادات التفصيلية",
  "revenues-by-category": "الإيرادات حسب الفئة",
  "revenues-by-payment": "الإيرادات حسب طريقة الدفع",
  "cheque-listing": "كشف الشيكات",
  "bank-transactions": "حركات البنوك",
  "bank-summary": "ملخص البنوك",
  "installment-plans": "خطط التقسيط",
  "installment-collections": "تحصيلات التقسيط",
  "installments-by-customer": "التقسيط حسب العميل",
  "installment-delinquent": "المتأخرات التقسيط",
  "branch-transfers": "التحويلات بين الفروع",
  "warehouse-levels": "أرصدة المخازن",
  "warehouse-levels-summary": "ملخص أرصدة المخازن",
  "employee-adjustments": "حوافز الموظفين",
  "user-list": "قائمة المستخدمين",
  "user-performance": "أداء المستخدمين",
  "login-history": "سجل تسجيل الدخول",
  "profit-by-category": "الربح حسب الفئة",
  "profit-by-customer": "الربح حسب العميل",
  "profit-by-period": "الربح حسب الفترة",
  "cost-movements": "تقرير حركات التكلفة",
  "cost-method-comparison": "مقارنة طرق التكلفة",
  "item-lifecycle": "دورة حياة الصنف",
  "margin-drift": "تغير الهامش والتكلفة",
  "inventory-turnover": "دوران المخزون وأيام التغطية",
  "cashier-override-impact": "أثر تجاوزات الكاشير",
  "stock-adjustment-audit": "تدقيق تسويات المخزون",
  "daily-owner-snapshot": "لقطة صاحب المحل اليومية",
  "ar-aging": "تقادم ذمم العملاء",
  "ap-aging": "تقادم ذمم الموردين",
  "top-customers": "أفضل العملاء",
  "collection-efficiency": "كفاءة التحصيل",
  "customer-loyalty": "ولاء العملاء",
  "supplier-reliability": "موثوقية الموردين",
  "customer-balance-list": "قائمة أرصدة العملاء",
  "supplier-balance-list": "قائمة أرصدة الموردين",
};

const AR_LABELS = {
  id: "المعرف",
  item_code: "كود الصنف",
  code: "الكود",
  sku: "SKU",
  barcode: "الباركود",
  item_id: "معرف الصنف",
  item_name: "اسم الصنف",
  name: "الاسم",
  invoice_no: "رقم الفاتورة",
  doc_no: "رقم المستند",
  purchase_no: "رقم الشراء",
  ref_no: "رقم المرجع",
  return_ref: "رقم المرتجع",
  customer_name: "العميل",
  supplier_name: "المورد",
  cashier: "الكاشير",
  handled_by: "تم بواسطة",
  created_by: "أنشئ بواسطة",
  full_name: "المستخدم",
  phone: "الهاتف",
  date: "التاريخ",
  created_at: "تاريخ الإنشاء",
  opened_date: "تاريخ الفتح",
  closed_at: "تاريخ الإغلاق",
  purchase_date: "تاريخ الشراء",
  last_purchase_date: "آخر تاريخ شراء",
  last_invoice_date: "آخر فاتورة",
  last_sale_date: "آخر بيع",
  last_movement_date: "آخر حركة",
  expiry_date: "تاريخ الصلاحية",
  total: "الإجمالي",
  subtotal: "قبل الخصم",
  gross_sales: "إجمالي المبيعات",
  net_sales: "صافي المبيعات",
  sales_total: "إجمالي المبيعات",
  total_sales: "إجمالي المبيعات",
  total_purchases: "إجمالي المشتريات",
  purchases_total: "إجمالي المشتريات",
  total_spent: "إجمالي الإنفاق",
  total_amount: "إجمالي المبلغ",
  total_billed: "إجمالي الفواتير",
  total_due: "إجمالي المستحق",
  total_cost: "إجمالي التكلفة",
  line_total: "إجمالي السطر",
  total_value: "إجمالي القيمة",
  total_value_wacc: "القيمة بمتوسط التكلفة",
  total_value_last_purchase: "القيمة بآخر شراء",
  total_discount: "إجمالي الخصم",
  discount_total: "إجمالي الخصم",
  discount: "الخصم",
  avg_discount: "متوسط الخصم",
  avg_discount_percent: "متوسط الخصم %",
  discount_range: "نطاق الخصم",
  return_discount: "خصم المرتجع",
  return_increase: "زيادة المرتجع",
  return_total: "صافي المرتجع",
  returns_total: "إجمالي المرتجعات",
  returns_amount: "قيمة المرتجعات",
  return_amount: "قيمة المرتجع",
  vat_reversed: "الضريبة المستردة",
  revenue: "الإيراد",
  cost: "التكلفة",
  cost_price: "سعر التكلفة",
  unit_price: "سعر الوحدة",
  unit_cost: "تكلفة الوحدة",
  wacc: "متوسط التكلفة",
  last_purchase_cost: "آخر تكلفة شراء",
  avg_unit_cost: "متوسط تكلفة الوحدة",
  avg_unit_price: "متوسط سعر الوحدة",
  sale_price: "سعر البيع",
  purchase_price: "سعر الشراء",
  gross_profit: "مجمل الربح",
  profit_margin: "هامش الربح",
  margin_percent: "هامش الربح %",
  current_margin_percent: "الهامش الحالي %",
  min_margin_percent: "الحد الأدنى %",
  suggested_price: "السعر المقترح",
  below_threshold: "تحت الحد",
  quantity: "الكمية",
  quantity_sold: "الكمية المباعة",
  quantity_purchased: "الكمية المشتراة",
  stock_quantity: "رصيد المخزون",
  system_quantity: "رصيد النظام",
  total_quantity: "إجمالي الكمية",
  before_qty: "الرصيد قبل",
  after_qty: "الرصيد بعد",
  min_stock_qty: "حد أدنى للمخزون",
  unit_name: "الوحدة",
  item_count: "عدد الأصناف",
  invoice_count: "عدد الفواتير",
  purchase_count: "عدد المشتريات",
  return_count: "عدد المرتجعات",
  returns_count: "عدد المرتجعات",
  cancelled_count: "الفواتير الملغاة",
  returns_handled: "المرتجعات المعالجة",
  items_returned: "الأصناف المرتجعة",
  transaction_count: "عدد المعاملات",
  action_count: "عدد العمليات",
  total_invoices: "عدد الفواتير",
  total_items_sold: "عدد الأصناف المباعة",
  distinct_suppliers: "عدد الموردين",
  supplier_count: "عدد الموردين",
  customer_count: "عدد العملاء",
  category_name: "الفئة",
  payment_type: "طريقة الدفع",
  status: "الحالة",
  type: "النوع",
  source: "المصدر",
  movement_type: "نوع الحركة",
  reference_type: "نوع المرجع",
  reference_id: "رقم المرجع",
  resource: "المورد",
  action: "الإجراء",
  payload_json: "التفاصيل",
  user_id: "المستخدم",
  warehouse_id: "المخزن",
  balance: "الرصيد",
  balance_label: "الاتجاه",
  opening_balance: "الرصيد الافتتاحي",
  closing_balance: "الرصيد الختامي",
  running_balance: "الرصيد الجاري",
  debit: "مدين",
  credit: "دائن",
  opening_cash: "النقدية الافتتاحية",
  closing_cash: "النقدية الختامية",
  expected_cash: "النقدية المتوقعة",
  cash_variance: "فرق النقدية",
  variance: "الفرق",
  collected: "المحصل",
  outstanding: "المستحق",
  collection_rate: "نسبة التحصيل %",
  days_to_collect: "أيام التحصيل",
  aging_0_30: "0-30 يوم",
  aging_31_60: "31-60 يوم",
  aging_61_90: "61-90 يوم",
  aging_90_plus: "أكثر من 90 يوم",
  days_until_expiry: "أيام حتى الصلاحية",
  days_since_last_movement: "أيام منذ آخر حركة",
  days_since_last_sale: "أيام منذ آخر بيع",
  aging_bucket: "فئة العمر",
  stock_status: "حالة المخزون",
  expiry_status: "حالة الصلاحية",
  tax_rate: "نسبة الضريبة",
  taxable_sales: "المبيعات الخاضعة",
  taxable_amount: "المبلغ الخاضع",
  vat_amount: "قيمة الضريبة",
  output_vat: "ضريبة المخرجات",
  input_vat: "ضريبة المدخلات",
  net_vat: "صافي الضريبة",
  amount: "المبلغ",
  pct: "النسبة %",
  section: "البند",
  label: "البيان",
  period: "الفترة",
  hour_slot: "الساعة",
  weekday: "يوم الأسبوع",
  weekday_name: "يوم الأسبوع",
  weekday_num: "رقم اليوم",
  avg_sale: "متوسط البيع",
  avg_transaction: "متوسط المعاملة",
  avg_invoice_value: "متوسط الفاتورة",
  avg_order_value: "متوسط الطلب",
  payment_method: "وسيلة الدفع",
  refund_method: "وسيلة الاسترداد",
  reason: "السبب",
  exception_type: "نوع الاستثناء",
  shift_id: "رقم الوردية",
  tx_count: "عدد الحركات",
  percentage: "النسبة %",
  running_total: "الإجمالي التراكمي",
  batch_no: "رقم الدفعة",
  potential_revenue: "إيراد محتمل",
  suggested_order_qty: "كمية الطلب المقترحة",
  estimated_order_cost: "تكلفة الطلب المقدرة",
  preferred_supplier: "المورد المفضل",
  loyalty_points: "نقاط الولاء",
  loyalty_tier: "شريحة الولاء",
  // ── Additional labels from actual SQL output ──
  gross_profit: "إجمالي الربح",
  total_gross_profit: "إجمالي الربح الإجمالي",
  gross_sales: "إجمالي المبيعات",
  net_sales: "صافي المبيعات",
  sales_total: "إجمالي المبيعات",
  avg_invoice_value: "متوسط قيمة الفاتورة",
  avg_transaction: "متوسط المعاملة",
  avg_order_value: "متوسط الطلب",
  avg_sale: "متوسط البيع",
  avg_discount: "متوسط الخصم",
  avg_unit_cost: "متوسط تكلفة الوحدة",
  avg_unit_price: "متوسط سعر الوحدة",
  running_balance: "الرصيد الجاري",
  opening_balance: "الرصيد الافتتاحي",
  closing_balance: "الرصيد الختامي",
  expected_cash: "النقدية المتوقعة",
  cash_variance: "فرق النقدية",
  opening_cash: "النقدية الافتتاحية",
  closing_cash: "النقدية الختامية",
  distinct_suppliers: "عدد الموردين المميزين",
  potential_revenue: "الإيراد المحتمل",
  suggested_order_qty: "كمية الطلب المقترحة",
  estimated_order_cost: "تكلفة الطلب المقدرة",
  preferred_supplier: "المورد المفضل",
  returns_handled: "المرتجعات المعالجة",
  items_returned: "الأصناف المرتجعة",
  payment_method: "وسيلة الدفع",
  refund_method: "وسيلة الاسترداد",
  exception_type: "نوع الاستثناء",
  tx_count: "عدد الحركات",
  percentage: "النسبة المئوية",
  running_total: "الإجمالي التراكمي",
  batch_no: "رقم الدفعة",
  opening_balance: "الرصيد الافتتاحي",
  net_vat: "صافي الضريبة",
  total_value: "القيمة الإجمالية",
  total_value_wacc: "القيمة (متوسط التكلفة)",
  total_value_last_purchase: "القيمة (آخر سعر شراء)",
  total_billed: "إجمالي الفواتير",
  total_due: "إجمالي المستحق",
  line_total: "إجمالي السطر",
  unit_price: "سعر الوحدة",
  unit_cost: "تكلفة الوحدة",
  sale_price: "سعر البيع",
  purchase_price: "سعر الشراء",
  current_margin_percent: "الهامش الحالي %",
  min_margin_percent: "الحد الأدنى للهامش %",
  suggested_price: "السعر المقترح",
  below_threshold: "تحت الحد الأدنى",
  stock_status: "حالة المخزون",
  expiry_status: "حالة الصلاحية",
  taxable_sales: "المبيعات الخاضعة للضريبة",
  taxable_amount: "المبلغ الخاضع للضريبة",
  vat_amount: "قيمة الضريبة",
  output_vat: "ضريبة المخرجات",
  input_vat: "ضريبة المدخلات",
  last_purchase_cost: "آخر تكلفة شراء",
  wacc: "متوسط التكلفة المرجح",
  profit_margin: "هامش الربح",
  margin_percent: "نسبة هامش الربح",
  item_name: "اسم الصنف",
  category_name: "اسم الفئة",
  customer_name: "اسم العميل",
  supplier_name: "اسم المورد",
  unit_name: "اسم الوحدة",
  weekday_name: "اسم اليوم",
  full_name: "الاسم الكامل",
  username: "اسم المستخدم",
  role: "الصلاحية",
  admin: "مدير",
  cashier: "كاشير",
  manager: "مشرف",
  status: "الحالة",
  last_login: "آخر تسجيل دخول",
  shift_count: "عدد الورديات",
  details: "التفاصيل",
  phone: "رقم الهاتف",
  invoice_no: "رقم الفاتورة",
  doc_no: "رقم المستند",
  purchase_no: "رقم المشتريات",
  ref_no: "رقم المرجع",
  return_ref: "رقم المرتجع",
  warehouse_id: "المخزن",
  cashier: "الكاشير",
  handled_by: "تم بواسطة",
  created_by: "أنشئ بواسطة",
  user_id: "المستخدم",
  action: "الإجراء",
  resource: "المورد",
  payload_json: "التفاصيل",
  movement_type: "نوع الحركة",
  reference_type: "نوع المرجع",
  reference_id: "رقم المرجع",
  before_qty: "الرصيد قبل",
  after_qty: "الرصيد بعد",
  min_stock_qty: "الحد الأدنى للكمية",
  stock_quantity: "كمية المخزون",
  system_quantity: "كمية النظام",
  total_quantity: "إجمالي الكمية",
  quantity_sold: "الكمية المباعة",
  quantity_purchased: "الكمية المشتراة",
  invoice_count: "عدد الفواتير",
  purchase_count: "عدد المشتريات",
  return_count: "عدد المرتجعات",
  returns_count: "عدد المرتجعات",
  cancelled_count: "عدد الملغاة",
  item_count: "عدد الأصناف",
  transaction_count: "عدد المعاملات",
  action_count: "عدد العمليات",
  total_invoices: "إجمالي الفواتير",
  total_items_sold: "إجمالي الأصناف المباعة",
  supplier_count: "عدد الموردين",
  customer_count: "عدد العملاء",
  days_until_expiry: "الأيام حتى الصلاحية",
  days_since_last_movement: "أيام منذ آخر حركة",
  days_since_last_sale: "أيام منذ آخر بيع",
  days_to_collect: "أيام التحصيل",
  aging_0_30: "0-30 يوم",
  aging_31_60: "31-60 يوم",
  aging_61_90: "61-90 يوم",
  aging_90_plus: "أكثر من 90 يوم",
  aging_bucket: "فئة العمر",
  collected: "المحصل",
  outstanding: "المستحق",
  collection_rate: "نسبة التحصيل",
  last_sale_date: "آخر تاريخ بيع",
  last_purchase_date: "آخر تاريخ شراء",
  last_invoice_date: "آخر تاريخ فاتورة",
  last_movement_date: "آخر تاريخ حركة",
  expiry_date: "تاريخ الصلاحية",
  // ── Previously-unmapped keys (were rendering as raw English) ──
  account_no: "رقم الحساب",
  adjustment_type: "نوع التسوية",
  available_balance: "الرصيد المتاح",
  avg_daily_sales: "متوسط المبيعات اليومية",
  avg_diff_pct: "متوسط الفرق %",
  avg_discount_pct: "متوسط الخصم %",
  avg_payment_days: "متوسط أيام السداد",
  avg_price_spread_percent: "متوسط تشتت السعر %",
  bank_name: "اسم البنك",
  category_count: "عدد الفئات",
  cheque_no: "رقم الشيك",
  cogs: "تكلفة البضاعة المباعة",
  cost_basis: "أساس التكلفة",
  cost_change: "تغيّر التكلفة",
  current_cost: "التكلفة الحالية",
  current_wacc: "متوسط التكلفة الحالي",
  days_of_stock: "أيام تغطية المخزون",
  days_overdue: "أيام التأخير",
  days_since_last_purchase: "أيام منذ آخر شراء",
  description: "الوصف",
  discount_invoice_count: "عدد فواتير الخصم",
  due_date: "تاريخ الاستحقاق",
  employee_name: "اسم الموظف",
  estimated_revenue_impact: "الأثر التقديري على الإيراد",
  expense_count: "عدد المصروفات",
  expenses: "المصروفات",
  first_period_cost: "تكلفة الفترة الأولى",
  from_warehouse: "من مخزن",
  gross_revenue: "إجمالي الإيراد",
  gross_spent: "إجمالي الإنفاق",
  installment_count: "عدد الأقساط",
  installment_no: "رقم القسط",
  inventory_value: "قيمة المخزون",
  last_period_cost: "تكلفة الفترة الأخيرة",
  last_return_date: "آخر تاريخ مرتجع",
  lifetime_gross_profit: "إجمالي الربح التراكمي",
  low_stock_alerts_count: "عدد تنبيهات نقص المخزون",
  margin_decline_percent: "نسبة تراجع الهامش %",
  net_profit: "صافي الربح",
  net_quantity_purchased: "صافي الكمية المشتراة",
  net_revenue: "صافي الإيراد",
  net_total_cost: "صافي إجمالي التكلفة",
  other_revenues: "إيرادات أخرى",
  overdue: "المتأخر",
  overdue_amount: "المبلغ المتأخر",
  overdue_receivables_count: "عدد الذمم المتأخرة",
  override_count: "عدد التعديلات",
  paid_amount: "المبلغ المدفوع",
  payee_name: "المستفيد",
  period_end: "نهاية الفترة",
  period_start: "بداية الفترة",
  plan_id: "رقم الخطة",
  previous_margin_percent: "الهامش السابق %",
  price_downs: "تخفيضات السعر",
  price_ups: "زيادات السعر",
  purchase_qty: "كمية الشراء",
  purchase_return_value: "قيمة مرتجع الشراء",
  purchase_value: "قيمة الشراء",
  qty_change: "تغيّر الكمية",
  qty_sold: "الكمية المباعة",
  quantity_returned: "الكمية المرتجعة",
  reference_no: "رقم المرجع",
  repeat_items: "الأصناف المتكررة",
  return_rate_percent: "نسبة المرتجعات %",
  returns_cost: "تكلفة المرتجعات",
  revenue_count: "عدد الإيرادات",
  running_quantity: "الكمية التراكمية",
  running_wacc: "متوسط التكلفة التراكمي",
  sales_cost: "تكلفة المبيعات",
  sales_qty: "كمية المبيعات",
  sales_return_value: "قيمة مرتجع المبيعات",
  sales_revenue: "إيراد المبيعات",
  source_doc_no: "رقم المستند المصدر",
  source_table: "المصدر",
  spread_min_max: "الفارق بين الأدنى والأعلى",
  start_date: "تاريخ البداية",
  stock_on_hand: "الرصيد المتاح",
  stock_velocity_status: "حالة دوران المخزون",
  to_warehouse: "إلى مخزن",
  total_expenses: "إجمالي المصروفات",
  total_header_discount: "إجمالي خصم الفاتورة",
  total_plans: "عدد الخطط",
  total_returns: "إجمالي المرتجعات",
  total_revenue: "إجمالي الإيراد",
  total_transactions: "عدد المعاملات",
  transfer_no: "رقم التحويل",
  treasury_name: "اسم الخزينة",
  turnover_ratio: "معدل الدوران",
  value_fifo: "القيمة (الوارد أولاً)",
  value_impact: "الأثر على القيمة",
  value_last: "القيمة (آخر تكلفة)",
  value_lifo: "القيمة (الوارد أخيراً)",
  value_wacc: "القيمة (متوسط التكلفة)",
  warehouse: "المخزن",
  warehouse_name: "المخزن",
  withdrawals: "المسحوبات",
  // ── Additional SQL aliases surfaced by specific queries ──
  avg_cost: "متوسط التكلفة",
  avg_expense: "متوسط المصروف",
  avg_revenue: "متوسط الإيراد",
  cashier_id: "الكاشير",
  cost_of_goods_sold: "تكلفة البضاعة المباعة",
  created_date: "تاريخ الإنشاء",
  customer_id: "العميل",
  debt_date: "تاريخ الدين",
  debt_total: "إجمالي الدين",
  discounts: "الخصومات",
  distinct_customers: "عدد العملاء",
  first_purchase_date: "أول تاريخ شراء",
  first_sale_date: "أول تاريخ بيع",
  last_cost: "آخر تكلفة",
  last_due_date: "آخر تاريخ استحقاق",
  last_expense_date: "آخر تاريخ مصروف",
  line_cost: "تكلفة السطر",
  line_discount: "خصم السطر",
  line_profit: "ربح السطر",
  low_stock_items: "أصناف تحت الحد",
  max_cost: "أعلى تكلفة",
  min_cost: "أدنى تكلفة",
  on_hand: "المتاح",
  outstanding_amount: "المبلغ المستحق",
  overdue_bucket: "فئة التأخير",
  paid_count: "عدد المدفوعات",
  party_id: "الطرف",
  party_type: "نوع الطرف",
  payment_breakdown: "تفاصيل الدفع",
  pending_count: "عدد المعلّقة",
  plan_count: "عدد الخطط",
  purchase_id: "رقم الشراء",
  purchase_return_qty: "كمية مرتجع الشراء",
  purchase_return_tx_count: "عدد معاملات مرتجع الشراء",
  purchase_tx_count: "عدد معاملات الشراء",
  remaining_pct: "نسبة المتبقي %",
  return_cost: "تكلفة المرتجع",
  return_revenue: "إيراد المرتجع",
  sales_return_qty: "كمية مرتجع المبيعات",
  sales_return_tx_count: "عدد معاملات مرتجع المبيعات",
  sales_tx_count: "عدد معاملات المبيعات",
  supplier_id: "المورد",
  total_deposits: "إجمالي الإيداعات",
  total_paid: "إجمالي المدفوع",
  total_remaining: "إجمالي المتبقي",
  total_revenues: "إجمالي الإيرادات",
  total_withdrawals: "إجمالي المسحوبات",
  transfer_in_qty: "الوارد (تحويل)",
  transfer_out_qty: "الصادر (تحويل)",
  transfer_tx_count: "عدد التحويلات",
  // ── Reconciliation columns: gross selling price + additions/fees ──
  selling_total: "إجمالي سعر البيع",
  additions_amount: "إضافة / رسوم",
  // ── Misc labels surfaced after the column-catalog re-sync ──
  reference: "المرجع",
  notes: "ملاحظات",
  drawer_name: "الساحب",
  min_stock: "الحد الأدنى للمخزون",
  remaining: "المتبقي",
  down_payment: "الدفعة المقدمة",
  frequency: "التكرار",
  installment_amount: "قيمة القسط",
  paid_at: "تاريخ السداد",
  net_purchases: "صافي المشتريات",
  potential_profit: "ربح محتمل",
  items_per_invoice: "أصناف لكل فاتورة",
  pct_of_sales: "نسبة من المبيعات %",
  pct_of_total: "النسبة من الإجمالي %",
  value_share_pct: "نسبة من قيمة المخزون %",
  avg_return_value: "متوسط قيمة المرتجع",
  net_flow: "صافي التدفق",
  frequency_monthly: "معدل الشراء شهرياً",
  days_since_last_purchase: "أيام منذ آخر شراء",
  first_invoice_date: "أول تاريخ شراء",
  last_collection_date: "آخر تاريخ تحصيل",
  partially_paid_count: "عدد المسدد جزئياً",
  fully_paid_count: "عدد المسدد بالكامل",
  total_sales: "إجمالي المبيعات",
  net_sales: "صافي المبيعات",
  return_rate_percent: "نسبة المرتجعات %",
  avg_payment_days: "متوسط أيام السداد",
  repeat_items: "الأصناف المتكررة",
  avg_price_spread_percent: "تشتت الأسعار %",
  overdue_amount: "المبلغ المتأخر",
  collection_rate: "نسبة التحصيل %",
  days_to_collect: "أيام التحصيل",
  total_billed: "إجمالي الفواتير",
  items_per_invoice: "أصناف لكل فاتورة",
  avg_discount_percent: "متوسط الخصم %",
  margin_percent: "هامش الربح %",
  gross_profit: "مجمل الربح",
  total_cost: "إجمالي التكلفة",
  returns_total: "إجمالي المرتجعات",
  invoice_count: "عدد الفواتير",
  purchase_count: "عدد المشتريات",
  // ── SQL aliases & columns missing from original AR_LABELS ──
  buys: "مشتريات",
  datetime: "التاريخ والوقت",
  doc_discount: "خصم المستند",
  doc_id: "رقم المستند",
  doc_increase: "إضافة المستند",
  doc_total: "إجمالي المستند",
  employee_id: "الموظف",
  line_sum: "مجموع البنود",
  net_total: "صافي الإجمالي",
  occurred_at: "تاريخ الحدوث",
  orig_ref: "المرجع الأصلي",
  ref_id: "رقم المرجع",
  source_id: "المصدر",
  source_line_id: "رقم سطر المصدر",
  tax_amount: "مبلغ الضريبة",
  tax_type: "نوع الضريبة",
  total_tax: "إجمالي الضريبة",
  updated_at: "آخر تحديث",
  v: "القيمة",
};

// Column order per report. Re-synced to the actual SQL output keys of each query
// (introspected against the live schema). Lists every column the query returns so the
// order is deterministic; technical join/grouping keys (customer_id, item_id, …) are
// placed last and hidden by default via INTERNAL_KEYS.
const REPORT_COLUMN_KEYS = {
  // ── Sales ──
  "daily-sales": ["date", "invoice_count", "selling_total", "total_discount", "additions_amount", "gross_sales", "total_cost", "returns_amount", "returns_count", "net_sales", "gross_profit", "avg_invoice_value", "margin_percent"],
  "detailed-sales": ["invoice_no", "date", "customer_name", "cashier", "payment_type", "status", "subtotal", "discount", "additions_amount", "total", "item_count", "payment_breakdown", "customer_id"],
  "sales-by-item": ["item_code", "item_name", "category_name", "quantity_sold", "revenue", "total_discount", "cost", "returns_amount", "returns_cost", "gross_profit", "margin_percent", "avg_unit_price", "selling_total", "avg_unit_cost", "wacc"],
  "sales-by-category": ["category_name", "item_count", "quantity_sold", "revenue", "total_discount", "cost", "returns_amount", "returns_cost", "gross_profit", "margin_percent", "selling_total", "avg_unit_cost"],
  "sales-by-cashier": ["cashier", "invoice_count", "cancelled_count", "total_sales", "total_discount", "avg_invoice_value", "total_items_sold", "total_cost", "returns_handled", "returns_cost", "net_sales", "gross_profit", "margin_percent", "items_per_invoice"],
  "sales-by-payment": ["payment_type", "invoice_count", "total_sales", "total_discount", "returns_amount", "avg_transaction", "net_sales", "pct_of_sales"],
  "sales-heatmap": ["weekday_name", "hour_slot", "invoice_count", "total_sales", "avg_sale", "weekday_num", "customer_id"],
  "exceptions": ["invoice_no", "date", "customer_name", "exception_type", "discount", "status", "total"],
  "period-comparison": ["period", "date", "invoice_count", "total_sales", "total_discount", "returns_amount", "net_sales", "total_cost", "gross_profit", "margin_percent", "avg_invoice_value"],
  "gross-net-sales": ["date", "invoice_count", "selling_total", "total_discount", "additions_amount", "gross_sales", "total_cost", "returns_amount", "net_sales", "gross_profit", "avg_invoice_value", "margin_percent"],
  "sales-returns": ["return_ref", "invoice_no", "date", "customer_name", "handled_by", "return_discount", "return_increase", "return_total", "reason", "refund_method", "items_returned", "id", "customer_id"],
  "discount-analysis": ["section", "payment_type", "discount_range", "invoice_count", "total_discount", "avg_discount", "avg_discount_percent", "total_sales"],
  "margin-by-item": ["item_code", "item_name", "category_name", "quantity_sold", "revenue", "cost", "returns_amount", "gross_profit", "margin_percent", "selling_total", "avg_unit_price", "avg_unit_cost", "wacc"],
  "margin-by-category": ["category_name", "quantity_sold", "revenue", "cost", "returns_amount", "gross_profit", "margin_percent", "selling_total", "avg_unit_cost"],
  "margin-health": ["item_name", "wacc", "sale_price", "current_margin_percent", "min_margin_percent", "suggested_price", "below_threshold", "item_id"],
  "shift-history": ["id", "cashier", "opened_date", "closed_at", "opening_cash", "closing_cash", "sales_total", "expected_cash", "cash_variance", "invoice_count", "status"],

  // ── Purchases ──
  "purchase-summary": ["date", "purchase_count", "distinct_suppliers", "total_discount", "additions_amount", "total_purchases", "avg_order_value"],
  "detailed-purchases": ["purchase_no", "date", "supplier_name", "total", "total_discount", "additions_amount", "status", "payment_type", "item_count", "created_by", "id", "supplier_id"],
  "purchases-by-supplier": ["supplier_name", "purchase_count", "total_purchases", "avg_order_value", "returns_total", "net_purchases", "last_purchase_date"],
  "purchases-by-item": ["item_code", "item_name", "quantity_purchased", "total_cost", "quantity_returned", "returns_cost", "net_quantity_purchased", "net_total_cost", "avg_unit_cost", "distinct_suppliers", "last_purchase_date"],
  "purchase-returns": ["return_ref", "supplier_name", "date", "return_discount", "return_increase", "return_total", "reason", "refund_method", "items_returned", "id"],
  "supplier-pricing": ["supplier_name", "item_name", "unit_price", "quantity", "line_total", "purchase_date"],

  // ── Inventory ──
  "slow-moving": ["item_code", "item_name", "category_name", "stock_quantity", "cost_price", "total_value", "potential_revenue", "potential_profit", "last_sale_date"],
  "stock-levels": ["item_code", "item_name", "category_name", "warehouse_name", "quantity", "min_stock_qty", "unit_name", "total_value", "stock_status", "wacc", "last_purchase_cost", "sale_price", "potential_revenue", "warehouse_id"],
  "stock-movements": ["item_code", "item_name", "warehouse_name", "movement_type", "reference_type", "reference_id", "before_qty", "after_qty", "quantity", "created_by", "date", "warehouse_id"],
  "stock-valuation": ["item_code", "name", "category_name", "warehouse_name", "total_quantity", "wacc", "last_purchase_cost", "purchase_price", "total_value", "sale_price", "potential_revenue", "item_id", "warehouse_id"],
  "count-sheet": ["item_code", "item_name", "barcode", "category_name", "warehouse_name", "system_quantity", "unit_name", "warehouse_id"],
  "reorder": ["item_code", "name", "quantity", "min_stock", "unit_name", "id"],
  "expiry": ["batch_no", "item_code", "item_name", "quantity", "expiry_date", "cost_price", "days_until_expiry", "expiry_status"],
  "inventory-aging": ["item_code", "item_name", "quantity", "wacc", "total_value", "last_movement_date", "days_since_last_movement", "aging_bucket"],
  "dead-stock": ["item_code", "item_name", "category_name", "quantity", "wacc", "total_value", "last_sale_date", "days_since_last_sale", "aging_bucket"],
  "cost-movements": ["date", "item_code", "item_name", "warehouse_name", "movement_type", "quantity", "unit_cost", "running_quantity", "running_wacc", "created_by", "source_doc_no", "source_table", "id", "item_id", "source_id", "source_line_id", "occurred_at", "created_at"],
  "cost-method-comparison": ["item_code", "item_name", "category_name", "quantity", "wacc", "last_cost", "value_wacc", "value_fifo", "value_lifo", "value_last", "spread_min_max", "item_id"],
  "item-lifecycle": ["item_code", "item_name", "category_name", "stock_on_hand", "current_wacc", "sale_price", "current_margin_percent", "purchase_qty", "purchase_value", "sales_qty", "sales_revenue", "sales_cost", "sales_return_value", "purchase_return_value", "lifetime_gross_profit", "total_transactions", "distinct_suppliers", "first_purchase_date", "last_purchase_date", "distinct_customers", "first_sale_date", "last_sale_date", "sales_return_qty", "purchase_return_qty", "transfer_in_qty", "transfer_out_qty", "item_id"],
  "margin-drift": ["item_code", "item_name", "category_name", "sale_price", "first_period_cost", "last_period_cost", "current_cost", "cost_change", "previous_margin_percent", "current_margin_percent", "margin_decline_percent", "item_id"],
  "inventory-turnover": ["item_code", "item_name", "category_name", "stock_on_hand", "inventory_value", "quantity_sold", "cogs", "avg_daily_sales", "days_of_stock", "turnover_ratio", "stock_velocity_status", "item_id"],
  "stock-adjustment-audit": ["date", "item_code", "item_name", "category_name", "warehouse_name", "qty_change", "before_qty", "after_qty", "cost_basis", "value_impact", "reason", "created_by", "id"],

  // ── Accounts ──
  "profit-loss": ["section", "label", "amount", "pct"],
  "customer-statement": ["date", "description", "debit", "credit", "running_balance", "item_name", "quantity", "unit_price", "line_total", "item_code"],
  "supplier-statement": ["date", "description", "debit", "credit", "running_balance", "item_name", "quantity", "unit_price", "line_total", "item_code"],
  "daily-owner-snapshot": ["period_start", "period_end", "invoice_count", "selling_total", "total_discount", "additions_amount", "gross_sales", "returns_amount", "net_sales", "cogs", "gross_profit", "expenses", "other_revenues", "withdrawals", "net_profit", "overdue_receivables_count", "low_stock_alerts_count"],

  // ── Treasury ──
  "cash-flow": ["date", "type", "total"],
  "treasury": ["name", "code", "balance", "source", "tx_count"],
  "cash-consistency": ["date", "shift_id", "cashier", "opening_cash", "closing_cash", "sales_total", "expected_cash", "cash_variance", "invoice_count", "status"],
  "payment-method-flow": ["payment_type", "date", "transaction_count", "total_amount", "running_total"],
  "bank-cash-split": ["type", "name", "balance", "percentage"],
  "reconciliation-exceptions": ["date", "shift_id", "cashier", "opening_cash", "closing_cash", "sales_total", "expected_cash", "cash_variance", "invoice_count", "status"],
  "daily-sessions": ["date", "cashier", "opening_cash", "closing_cash", "sales_total", "total_discount", "invoice_count", "cash_variance", "status"],
  "withdrawals-report": ["reference_no", "date", "amount", "reason", "payment_method", "created_by", "id"],

  // ── Tax ──
  "vat": ["tax_rate", "taxable_sales", "vat_amount", "invoice_count"],
  "output-vat": ["tax_rate", "taxable_amount", "vat_amount", "invoice_count", "customer_count"],
  "input-vat": ["tax_rate", "taxable_amount", "vat_amount", "purchase_count", "supplier_count"],
  "vat-filing-summary": ["sales_total", "output_vat", "purchases_total", "input_vat", "net_vat"],
  "returns-tax-effect": ["return_ref", "date", "return_amount", "vat_reversed", "items_returned", "customer_id"],

  // ── Audit / Users ──
  "audit-log": ["id", "full_name", "action", "resource", "payload_json", "created_at", "user_id"],
  "user-activity": ["full_name", "action", "resource", "action_count", "date", "user_id"],
  "user-list": ["id", "username", "full_name", "role", "status", "created_at", "last_login", "updated_at"],
  "user-performance": ["full_name", "invoice_count", "total_sales", "total_discount", "avg_invoice_value", "returns_handled", "returns_amount", "shift_count", "user_id"],
  "login-history": ["full_name", "action", "date", "details", "resource", "id", "user_id"],

  // ── Sales / Purchase returns summaries ──
  "sales-returns-summary": ["date", "return_count", "returns_total", "customer_count", "items_returned", "avg_return_value"],
  "sales-returns-by-customer": ["customer_name", "return_count", "returns_total", "avg_return_value", "last_return_date"],
  "purchase-returns-summary": ["date", "return_count", "returns_total", "supplier_count", "items_returned"],
  "purchase-returns-by-supplier": ["supplier_name", "return_count", "returns_total", "last_return_date"],

  // ── Expenses / Revenues ──
  "expense-summary": ["date", "expense_count", "total_expenses", "avg_expense", "category_count"],
  "detailed-expenses": ["date", "category_name", "amount", "payment_method", "description", "notes", "employee_id"],
  "expenses-by-category": ["category_name", "expense_count", "total_expenses", "avg_expense", "pct_of_total", "last_expense_date"],
  "expenses-by-payment": ["payment_method", "expense_count", "total_expenses", "avg_expense"],
  "revenue-summary": ["date", "revenue_count", "total_revenues", "avg_revenue", "category_count"],
  "detailed-revenues": ["date", "category_name", "amount", "payment_type", "description", "notes"],
  "revenues-by-category": ["category_name", "revenue_count", "total_revenues", "avg_revenue", "pct_of_total"],
  "revenues-by-payment": ["payment_method", "revenue_count", "total_revenues", "avg_revenue"],

  // ── Cheques / Banks ──
  "cheque-listing": ["cheque_no", "bank_name", "type", "amount", "due_date", "status", "drawer_name", "created_date", "notes", "id", "party_type", "party_id"],
  "bank-transactions": ["date", "bank_name", "type", "amount", "reference", "notes", "id"],
  "bank-summary": ["name", "balance", "transaction_count", "total_deposits", "total_withdrawals", "net_flow"],

  // ── Installments ──
  "installment-plans": ["id", "customer_name", "total", "paid_amount", "remaining", "down_payment", "frequency", "installment_count", "installment_amount", "due_date", "status", "remaining_pct", "created_date", "paid_at"],
  "installment-collections": ["id", "customer_name", "installment_amount", "due_date", "paid_at", "status", "remaining", "total"],
  "installments-by-customer": ["customer_name", "plan_count", "total_amount", "total_paid", "total_remaining", "last_due_date", "paid_count", "pending_count"],
  "installment-delinquent": ["id", "customer_name", "total", "remaining", "installment_amount", "due_date", "days_overdue", "overdue_bucket"],

  // ── Warehouses ──
  "branch-transfers": ["reference_no", "date", "type", "warehouse_name", "item_count", "notes", "created_by", "id"],
  "warehouse-levels": ["warehouse_name", "item_count", "total_quantity", "total_value", "low_stock_items", "value_share_pct"],
  "warehouse-levels-summary": ["warehouse_name", "item_count", "total_quantity", "total_value", "low_stock_items", "value_share_pct"],
  "employee-adjustments": ["date", "employee_name", "adjustment_type", "amount", "reason", "created_by", "id"],

  // ── Profit ──
  "profit-by-category": ["category_name", "quantity_sold", "selling_total", "revenue", "cost", "returns_amount", "gross_profit", "margin_percent", "avg_unit_price", "avg_unit_cost"],
  "profit-by-customer": ["customer_name", "invoice_count", "selling_total", "total_discount", "additions_amount", "revenue", "cost", "returns_amount", "gross_profit", "margin_percent", "avg_invoice_value"],
  "profit-by-period": ["date", "invoice_count", "selling_total", "total_discount", "additions_amount", "revenue", "cost_of_goods_sold", "returns_amount", "gross_profit", "expenses", "net_profit", "margin_percent", "avg_invoice_value"],

  // ── Sales analytics ──
  "cashier-override-impact": ["cashier", "override_count", "price_downs", "price_ups", "estimated_revenue_impact", "avg_diff_pct", "discount_invoice_count", "total_header_discount", "avg_discount_pct", "cashier_id"],

  // ── Customer Reports ──
  "ar-aging": ["customer_name", "total_due", "aging_0_30", "aging_31_60", "aging_61_90", "aging_90_plus", "overdue_amount", "last_invoice_date", "phone", "invoice_count"],
  "top-customers": ["customer_name", "total_sales", "net_sales", "gross_profit", "margin_percent", "avg_invoice_value", "invoice_count", "last_invoice_date", "phone", "returns_total", "total_cost"],
  "collection-efficiency": ["customer_name", "total_billed", "collected", "collection_rate", "outstanding", "invoice_count", "partially_paid_count", "fully_paid_count"],
  "customer-loyalty": ["customer_name", "total_sales", "invoice_count", "avg_invoice_value", "frequency_monthly", "items_per_invoice", "avg_discount_percent", "returns_total", "last_invoice_date", "phone", "first_invoice_date", "days_since_last_purchase"],
  "customer-balance-list": ["customer_name", "phone", "balance", "balance_label"],

  // ── Supplier Reports ──
  "ap-aging": ["supplier_name", "total_due", "aging_0_30", "aging_31_60", "aging_61_90", "aging_90_plus", "overdue_amount", "last_purchase_date", "phone", "purchase_count"],
  "supplier-reliability": ["supplier_name", "total_purchases", "purchase_count", "return_rate_percent", "avg_payment_days", "avg_price_spread_percent", "total_returns", "return_count", "last_purchase_date", "phone", "repeat_items"],
  "supplier-balance-list": ["supplier_name", "phone", "balance", "balance_label"],
};

// Extra analytics columns per report: shipped with the data and toggleable from the
// "الأعمدة" picker, but hidden by default so the default layout stays focused.
const REPORT_EXTRA_KEYS = {
  "daily-sales": new Set(["avg_invoice_value", "margin_percent"]),
  "gross-net-sales": new Set(["avg_invoice_value", "margin_percent"]),
  "sales-by-item": new Set(["selling_total", "avg_unit_cost", "wacc"]),
  "margin-by-item": new Set(["selling_total", "avg_unit_price", "avg_unit_cost", "wacc"]),
  "sales-by-category": new Set(["selling_total", "avg_unit_cost"]),
  "margin-by-category": new Set(["selling_total", "avg_unit_cost"]),
  "sales-by-cashier": new Set(["margin_percent", "items_per_invoice"]),
  "sales-by-payment": new Set(["net_sales", "pct_of_sales"]),
  "period-comparison": new Set(["margin_percent", "avg_invoice_value"]),
  "sales-returns-summary": new Set(["avg_return_value"]),
  "sales-returns-by-customer": new Set(["avg_return_value"]),
  "purchases-by-supplier": new Set(["net_purchases"]),
  "stock-levels": new Set(["wacc", "last_purchase_cost", "sale_price", "potential_revenue"]),
  "stock-valuation": new Set(["sale_price", "potential_revenue"]),
  "slow-moving": new Set(["potential_profit"]),
  "warehouse-levels": new Set(["value_share_pct"]),
  "warehouse-levels-summary": new Set(["value_share_pct"]),
  "vat-filing-summary": new Set(["net_vat"]),
  "expenses-by-category": new Set(["pct_of_total"]),
  "revenues-by-category": new Set(["pct_of_total"]),
  "bank-summary": new Set(["net_flow"]),
  "customer-statement": new Set(["amount", "item_code", "barcode"]),
  "supplier-statement": new Set(["amount", "item_code", "barcode"]),
  "profit-by-customer": new Set(["avg_invoice_value"]),
  "profit-by-period": new Set(["margin_percent", "avg_invoice_value"]),
  "profit-by-category": new Set(["avg_unit_price", "avg_unit_cost"]),
  "ar-aging": new Set(["phone", "invoice_count"]),
  "ap-aging": new Set(["phone", "purchase_count"]),
  "top-customers": new Set(["phone", "returns_total", "total_cost"]),
  "collection-efficiency": new Set(["partially_paid_count", "fully_paid_count"]),
  "supplier-reliability": new Set(["phone", "repeat_items"]),
  "customer-loyalty": new Set(["phone", "first_invoice_date", "days_since_last_purchase"]),
  "customer-balance-list": new Set([]),
  "supplier-balance-list": new Set([]),
};

const CODE_KEYS = new Set(["id", "item_code", "code", "sku", "barcode", "invoice_no", "purchase_no", "ref_no", "return_ref", "reference_id", "shift_id", "user_id", "warehouse_id", "batch_no", "section"]);
const DATE_KEYS = new Set(["date", "created_at", "opened_date", "closed_at", "purchase_date", "last_purchase_date", "last_invoice_date", "last_sale_date", "last_movement_date", "expiry_date", "updated_at"]);
const PERCENT_KEYS = new Set(["pct", "margin_percent", "current_margin_percent", "min_margin_percent", "avg_discount_percent", "collection_rate", "percentage", "tax_rate", "avg_discount_percent", "collection_rate", "pct_of_sales", "pct_of_total", "value_share_pct"]);
const NUMBER_KEYS = new Set(["quantity", "quantity_sold", "quantity_purchased", "stock_quantity", "system_quantity", "total_quantity", "before_qty", "after_qty", "min_stock_qty", "item_count", "invoice_count", "purchase_count", "returns_count", "return_count", "items_returned", "transaction_count", "action_count", "total_invoices", "total_items_sold", "distinct_suppliers", "supplier_count", "customer_count", "tx_count", "days_until_expiry", "days_since_last_movement", "days_since_last_sale", "days_to_collect", "weekday_num", "cancelled_count", "loyalty_points", "suggested_order_qty", "returns_handled", "weekday_num", "shift_count", "items_per_invoice"]);

// Money keys that lack an obvious substring match below (e.g. WACC).
const MONEY_KEYS = new Set(["wacc", "current_wacc", "running_wacc", "net_purchases", "selling_total", "net_flow"]);

function inferType(key) {
  if (CODE_KEYS.has(key)) return "code";
  if (DATE_KEYS.has(key) || key.endsWith("_date")) return "date";
  if (PERCENT_KEYS.has(key) || key.endsWith("_percent")) return "percent";
  if (NUMBER_KEYS.has(key) || key.endsWith("_count")) return "number";
  if (MONEY_KEYS.has(key)) return "money";
  if (key.includes("price") || key.includes("cost") || key.includes("total") || key.includes("amount") || key.includes("balance") || key.includes("sales") || key.includes("profit") || key.includes("discount") || key.includes("increase") || key.includes("vat") || key.includes("cash") || key.includes("revenue") || key.includes("value") || key.includes("collected") || key.includes("outstanding") || key.includes("due")) return "money";
  return "text";
}

function inferPriority(key, index) {
  if (INTERNAL_KEYS.has(key)) return "optional";
  if (index < 5) return "essential";
  if (index < 9) return "useful";
  return "optional";
}

// Technical/internal columns: kept available (toggleable) but hidden by default
// so reports don't surface raw plumbing (JSON blobs, source-table names, helper ids).
const INTERNAL_KEYS = new Set([
  "payload_json", "source_table", "source_doc_no", "weekday_num", "party_type",
  "party_id", "reference_id", "reference_type", "plan_id",
  // Join/grouping keys that duplicate a human-readable column already shown
  // (e.g. customer_id alongside customer_name). Kept available but hidden by default.
  "customer_id", "supplier_id", "cashier_id", "item_id", "warehouse_id", "user_id",
  "employee_id", "source_id", "source_line_id",
]);

function labelForKey(key) {
  return AR_LABELS[key] || key;
}

// How many *core* (non-extra, non-internal) columns are visible by default.
const MAX_DEFAULT_VISIBLE = 12;

function buildColumn(key, coreIndex = 0, hidden = false) {
  return {
    key,
    label: labelForKey(key),
    type: inferType(key),
    printPriority: hidden ? "optional" : inferPriority(key, coreIndex),
    // Hidden (extra/internal) columns never take a visible slot, so appending extras
    // can't bump a core column (e.g. gross_profit) out of the default view.
    defaultVisible: !hidden && coreIndex < MAX_DEFAULT_VISIBLE,
  };
}

function orderKeys(keys, slug) {
  const preferred = REPORT_COLUMN_KEYS[slug] || [];
  const used = new Set();
  const ordered = [];
  preferred.forEach((key) => {
    if (keys.includes(key) && !used.has(key)) {
      ordered.push(key);
      used.add(key);
    }
  });
  keys.forEach((key) => {
    if (!used.has(key)) ordered.push(key);
  });
  return ordered;
}

function getReportColumns(slug, rows = []) {
  const rowKeys = Object.keys(rows?.[0] || {});
  const catalogKeys = REPORT_COLUMN_KEYS[slug] || [];
  const keys = rowKeys.length ? orderKeys(rowKeys, slug).filter(k => !k.startsWith('_')) : catalogKeys;
  const extras = REPORT_EXTRA_KEYS[slug];
  let coreIndex = 0;
  return keys.map((key) => {
    const hidden = INTERNAL_KEYS.has(key) || (extras ? extras.has(key) : false);
    return buildColumn(key, hidden ? Infinity : coreIndex++, hidden);
  });
}

function getReportTitle(slug, fallback = "") {
  return REPORT_TITLES[slug] || fallback || slug;
}

function getReportDescription(slug) {
  return REPORT_DESCRIPTIONS[slug] || "";
}

function normalizeStructuredReport(data) {
  if (!data || typeof data !== "object" || Array.isArray(data)) return null;
  if (Array.isArray(data.rows)) {
    return {
      rows: data.rows,
      sections: Array.isArray(data.sections) ? data.sections : [],
      summary: data.summary || null,
    };
  }
  if (Array.isArray(data.transactions)) {
    const summary = { ...data };
    delete summary.transactions;
    return { rows: data.transactions, sections: [], summary };
  }
  const sections = [];
  ["by_payment", "by_range"].forEach((key) => {
    if (Array.isArray(data[key])) {
      const sectionLabel = key === "by_payment" ? "حسب طريقة الدفع" : "حسب نطاق الخصم";
      sections.push({ key, label: sectionLabel, rows: data[key] });
    }
  });
  if (sections.length) {
    const rows = sections.flatMap((section) => section.rows.map((row) => ({ section: section.label, ...row })));
    return { rows, sections, summary: null };
  }
  return null;
}

module.exports = {
  REPORT_COLUMN_KEYS,
  REPORT_TITLES,
  REPORT_DESCRIPTIONS,
  labelForKey,
  getReportColumns,
  getReportTitle,
  getReportDescription,
  normalizeStructuredReport,
};
