const REPORT_DESCRIPTIONS = {
  // ── تقارير العملاء ──
  "ar-aging": "يعرض توزيع الذمم المدينة على العملاء حسب فترات التقادم (0-30، 31-60، 61-90، +90 يوماً) مع إجمالي المستحق والمتأخر، لتحديد العملاء المتعثرة ذممهم ومتابعة التحصيل.",
  "top-customers": "يكشف عن أهم العملاء من حيث إجمالي المبيعات وصافيها مع هامش الربح ومتوسط الفاتورة، لتمكين استراتيجيات البيع والولاء للعملاء الأكثر ربحية.",
  "collection-efficiency": "يحلل كفاءة تحصيل المستحقات لكل عميل من خلال إجمالي الفواتير والمحصل والمستحق ونسبة التحصيل، لقياس أداء إدارة الائتمان والتنبؤ بالتدفق النقدي.",
  "customer-loyalty": "يقيس ولاء العملاء من خلال تواتر الشراء الشهري ومتوسط قيمة الفاتورة ونسبة الخصم والمرتجعات، لتحديد العملاء المخلصين ومنحهم أولوية في العروض والحوافز.",
  "customer-balance-list": "يعرض جميع العملاء مع أرصدتهم الحالية (مديون أو دائن) مرتبة تنازلياً حسب قيمة الرصيد. يتم إخفاء العملاء ذوي الرصيد الصفري.",
  "customer-statement": "يعرض كشف حساب مفصل لعميل معين يشمل جميع الفواتير والمدفوعات والمرتجعات والأرصدة خلال فترة زمنية محددة، لمتابعة حركة الحساب بدقة.",

  // ── تقارير الموردين ──
  "ap-aging": "يعرض توزيع الذمم الدائنة على الموردين حسب فترات التقادم (0-30، 31-60، 61-90، +90 يوماً) مع إجمالي المستحق، لإدارة السيولة النقدية وتحديد أولويات السداد.",
  "supplier-reliability": "يقيم موثوقية الموردين بناءً على نسبة المرتجعات ومتوسط أيام السداد وتشتت الأسعار وتكرار الطلبات، لاختيار الموردين الأفضل أداءً والأكثر استقراراً في التسعير.",
  "supplier-balance-list": "يعرض جميع الموردين مع أرصدتهم الحالية (دائن أو مديون) مرتبة تنازلياً حسب قيمة الرصيد. يتم إخفاء الموردين ذوي الرصيد الصفري.",
  "supplier-statement": "يعرض كشف حساب مفصل لمورد معين يشمل جميع المشتريات والمدفوعات والمرتجعات والأرصدة خلال فترة زمنية محددة، لمتابعة الذمم الدائنة.",

  // ── تقارير المبيعات ──
  "daily-sales": "يعرض ملخصاً يومياً للمبيعات يشمل إجمالي الفواتير والكميات المباعة ومتوسط الفاتورة والإرجاعات، مع إمكانية المقارنة بالفترة السابقة وتحديد الاتجاهات اليومية.",
  "detailed-sales": "يعرض جميع فواتير البيع بالتفصيل مع تاريخ الفاتورة والعميل والكاشير وإجمالي المبلغ والخصم وطريقة الدفع، لفحص المعاملات الفردية.",
  "sales-by-item": "يحلل المبيعات حسب كل صنف مع إجمالي الكمية المباعة والإيرادات والتكلفة وهامش الربح، لتحديد الأصناف الأكثر مبيعاً والأعلى ربحية.",
  "sales-by-category": "يجمع المبيعات حسب فئات الأصناف مع إجمالي المبيعات والتكلفة والربح لكل فئة، لمقارنة أداء الفئات المختلفة.",
  "sales-by-cashier": "يعرض أداء المبيعات لكل كاشير من حيث إجمالي الفواتير والكمية ومتوسط الفاتورة، لتقييم أداء الموظفين ومكافأة الأفضل.",
  "sales-by-payment": "يوزع المبيعات حسب طرق الدفع (نقداً، آجل، بطاقة، تحويل) مع إجمالي المبيعات لكل طريقة، لتحليل تفضيلات الدفع لدى العملاء.",
  "sales-heatmap": "يعرض خريطة كثافة المبيعات على شكل مصفوفة أيام × ساعات توضح أوقات الذروة وفترات الركود، لتحسين جداول العمل والعروض الترويجية.",
  "period-comparison": "يقارن أداء المبيعات بين فترتين زمنيتين مختلفتين مع نسبة التغير في الإيرادات والكمية والربح، لقياس أثر القرارات التجارية.",
  "shift-history": "يعرض سجل ورديات الكاشير مع تفاصيل الفتح والإغلاق والفرق النقدي والمبيعات خلال كل وردية، لمتابعة أداء الكاشيرز.",
  "gross-net-sales": "يقارن إجمالي المبيعات قبل الخصم وبعده مع صافي المبيعات وإجمالي الخصومات والمرتجعات، لحساب صافي الإيرادات بدقة.",
  "sales-returns": "يعرض جميع مرتجعات المبيعات مع تفاصيل العميل والصنف والكمية والسبب، لتحليل أسباب الإرجاع وتقليل نسبته.",
  "sales-returns-summary": "ملخص إجمالي مرتجعات المبيعات خلال الفترة مع إجمالي قيمة المرتجع والكمية وعدد المعاملات، لمتابعة اتجاهات الإرجاع.",
  "sales-returns-by-customer": "يحلل مرتجعات المبيعات حسب كل عميل مع إجمالي قيمة وعدد المرتجعات، لتحديد العملاء الأكثر إرجاعاً واتخاذ الإجراءات المناسبة.",
  "discount-analysis": "يحلل الخصومات الممنوحة في المبيعات حسب نوع الخصم وطريقة الدفع والكاشير، مع إجمالي الخصم ونسبة من المبيعات.",
  "margin-by-item": "يعرض هامش الربح لكل صنف مع سعر البيع والتكلفة وهامش الربح المطلق والنسبي، لتسعير الأصناف بدقة.",
  "margin-by-category": "يجمع هوامش الربح حسب فئات الأصناف مع متوسط هامش الربح لكل فئة، لمقارنة ربحية الفئات.",
  "margin-health": "يقيم صحة هوامش الربح من خلال عرض الأصناف التي يقل هامش ربحها عن الحد الأدنى المحدد، للتنبيه بتسعير غير مناسب.",
  "cashier-override-impact": "يقيس الأثر المالي لتجاوزات الكاشير على الأسعار (تخفيض أو رفع) مع إجمالي أثر التجاوز على الإيرادات ومقارنة متوسط الخصم، لمراقبة صلاحيات الكاشير.",
  "margin-drift": "يرصد تغير هامش الربح وتكلفة الأصناف عبر الفترات مع مقارنة هامش الربح السابق مقابل الحالي ونسبة الانخفاض، للكشف عن تآكل الهوامش.",

  // ── تقارير المشتريات ──
  "purchase-summary": "يعرض ملخصاً للمشتريات خلال الفترة مع إجمالي الفواتير والكمية المشتراة وإجمالي التكلفة، لمتابعة نشاط الشراء.",
  "detailed-purchases": "يعرض جميع فواتير المشتريات بالتفصيل مع المورد والتاريخ والإجمالي والحالة وطريقة الدفع، لفحص المعاملات الفردية.",
  "purchases-by-supplier": "يجمع المشتريات حسب كل مورد مع إجمالي الكمية والتكلفة وعدد الفواتير، لتقييم حجم التعامل مع كل مورد.",
  "purchases-by-item": "يحلل المشتريات حسب الصنف مع إجمالي الكمية المشتراة والتكلفة لكل صنف، لمتابعة مخزون المشتريات.",
  "purchase-returns": "يعرض مرتجعات المشتريات مع تفاصيل المورد والصنف والكمية والسبب، لمتابعة الموردين غير الملتزمين.",
  "purchase-returns-summary": "ملخص إجمالي مرتجعات المشتريات مع إجمالي القيمة والكمية خلال الفترة، لمتابعة اتجاهات الإرجاع مع الموردين.",
  "purchase-returns-by-supplier": "يحلل مرتجعات المشتريات حسب كل مورد لتحديد الموردين ذوي المرتجعات العالية، لتحسين اختيار الموردين.",
  "supplier-pricing": "يقارن أسعار الموردين لنفس الأصناف مع آخر سعر شراء وتاريخه، لاختيار أفضل سعر وجودة.",

  // ── تقارير المخزون ──
  "slow-moving": "يكشف الأصناف بطيئة الحركة بناءً على مبيعات الأشهر الثلاثة الأخيرة مع الكمية المتاحة وتكلفتها، للتخلص من المخزون الراكد.",
  "stock-levels": "يعرض أرصدة المخزون الحالية لكل صنف مع الكمية وتكلفة الوحدة وإجمالي القيمة بطرق التكلفة المختلفة، لجرد المخزون.",
  "stock-movements": "يعرض حركات المخزون من إدخال وإخراج وتحويل مع تاريخ الحركة ونوعها والكمية والمرجع، لتدقيق المخزون.",
  "stock-valuation": "يقيم المخزون بقيمته وفقاً لطرق التكلفة (متوسط التكلفة، آخر شراء) مع إجمالي قيمة المخزون، لإعداد القوائم المالية.",
  "count-sheet": "كشف جرد فارغ للأصناف في المخازن يمكن طباعته للتعبئة اليدوية أثناء عملية الجرد الفعلي.",
  "reorder": "يعرض الأصناف التي وصلت إلى حد إعادة الطلب أو أقل مع المورد الموصى به وآخر سعر شراء، لتنبيه المشتريات.",
  "expiry": "يكشف الأصناف التي تقترب من تاريخ انتهاء الصلاحية أو انتهت صلاحيتها مع الكمية المتبقية وتاريخ الصلاحية، لتجنب التلف.",
  "inventory-aging": "يحلل أعمار المخزون حسب فترات التخزين مع الكمية والقيمة لكل فترة، لتحديد المخزون القديم.",
  "dead-stock": "يعرض الأصناف التي لم يحدث لها أي حركة بيع خلال فترة محددة مع الكمية المتاحة وتكلفتها، لاتخاذ قرار التصفية.",
  "cost-movements": "يعرض حركات التكلفة للأصناف مع تفاصيل الحركة ونوعها والكمية والتكلفة قبل وبعد الحركة، لتدقيق التكاليف.",
  "cost-method-comparison": "يقارن تقييم المخزون بطرق التكلفة المختلفة (متوسط التكلفة، آخر شراء) مع الفروق لكل صنف، لاختيار طريقة التكلفة.",
  "item-lifecycle": "يعرض دورة حياة الصنف الكاملة من أول شراء إلى آخر بيع مع التغير في السعر والتكلفة والهامش، لتحليل أداء الصنف.",
  "inventory-turnover": "يحسب معدل دوران المخزون وأيام التغطية لكل صنف بناءً على تكلفة البيع ومتوسط المخزون، لقياس كفاءة المخزون.",
  "stock-adjustment-audit": "يعرض جميع تسويات المخزون مع تفاصيل الصنف والكمية قبل وبعد التسوية والفرق والسبب والمستخدم، لتدقيق التعديلات.",

  // ── تقارير الحسابات ──
  "profit-loss": "يعرض قائمة الأرباح والخسائر شاملاً إجمالي المبيعات وتكلفة البيع وإجمالي الربح والمصروفات والإيرادات الأخرى وصافي الربح.",
  "daily-owner-snapshot": "لقطة سريعة لأداء المحل اليومي تشمل إجمالي المبيعات والمشتريات والمصروفات والإيرادات والأرصدة النقدية والأرباح المقدرة.",

  // ── تقارير الخزينة ──
  "cash-flow": "يعرض التدفق النقدي التفصيلي لجميع حركات الخزينة مع الإيرادات والمصروفات والرصيد التراكمي، لمتابعة السيولة النقدية.",
  "treasury": "يعرض أرصدة الخزائن والبنوك الحالية لكل حساب مع آخر حركة، للحصول على لمحة سريعة عن الوضع النقدي.",
  "cash-consistency": "يقارن بين النقدية الفعلية المتوقعة من المبيعات والنقدية المسجلة في النظام لاكتشاف الفروقات في الخزينة.",
  "payment-method-flow": "يعرض تدفق حركات الدفع لكل وسيلة دفع مع إجمالي الداخل والخارج والرصيد التراكمي، لمتابعة حركة وسائل الدفع.",
  "payment-flow-summary": "ملخص تدفقات وسائل الدفع مع إجمالي الداخل والخارج وصافي الحركة لكل وسيلة دفع، لمتابعة التوزيع النقدي.",
  "payment-flow-ledger": "سجل تفصيلي لجميع حركات الدفع مع تاريخ الحركة ونوع المستند والطرف والوسيلة والمبلغ، لتدقيق المدفوعات.",
  "payment-flow-by-doc-type": "يحلل تدفقات الدفع حسب نوع المستند (فاتورة بيع، تسوية، تحصيل، سداد) مع إجمالي المبالغ لكل نوع.",
  "payment-flow-by-direction": "يعرض تدفقات الدفع حسب الاتجاه (داخل/خارج) مع تفصيل وسيلة الدفع ونوع المستند، لتحليل التدفقات النقدية الداخلة والخارجة.",
  "payment-flow-running": "يعرض الرصيد التراكمي لوسائل الدفع مع تفاصيل الحركة والمبلغ والرصيد بعد كل حركة، لتتبع الأرصدة لحظة بلحظة.",
  "bank-cash-split": "يعرض توزيع الأرصدة النقدية بين الخزينة والبنوك مع إجمالي النقدية المتاحة، لمعرفة تركيز السيولة.",
  "reconciliation-exceptions": "يكشف حالات عدم التطابق بين الأرصدة المتوقعة والفعلية في الخزينة مع تفاصيل الفروقات والوردية والكاشير.",
  "daily-sessions": "يعرض جلسات الخزينة اليومية مع إجمالي المبيعات النقدية والمصروفات والإيرادات وصافي الجلسة لكل خزينة.",
  "withdrawals-report": "يعرض جميع حركات السحوبات من الخزينة مع تفاصيل المستفيد والمبلغ والغرض والتاريخ، لمتابعة المسحوبات النقدية.",

  // ── تقارير الضرائب ──
  "vat": "يعرض تفاصيل ضريبة القيمة المضافة على المبيعات مع مبلغ الضريبة وصافي الفاتورة بعد الضريبة، لحساب الالتزام الضريبي.",
  "output-vat": "يعرض ضريبة المخرجات (الضريبة على المبيعات) مع تفاصيل الفواتير والضريبة المحصلة، لإعداد إقرار ضريبة المخرجات.",
  "input-vat": "يعرض ضريبة المدخلات (الضريبة على المشتريات) مع تفاصيل فواتير الشراء والضريبة المسددة، لخصم ضريبة المدخلات.",
  "vat-filing-summary": "ملخص الإقرار الضريبي يشمل إجمالي ضريبة المخرجات وضريبة المدخلات وصافي الضريبة المستحقة للحكومة.",
  "returns-tax-effect": "يحسب الأثر الضريبي للمرتجعات (مبيعات ومشتريات) مع ضريبة المرتجعات المستردة وتأثيرها على صافي الالتزام الضريبي.",

  // ── تقارير التدقيق ──
  "exceptions": "يعرض استثناءات المبيعات (فواتير ملغاة، خصومات استثنائية، تجاوزات أسعار) مع تفاصيل المخالفة والكاشير، لتدقيق الحالات غير الطبيعية.",
  "audit-log": "سجل التدقيق الكامل لجميع الإجراءات في النظام مع المستخدم والإجراء والموارد والتاريخ، لتتبع التغييرات للأغراض الرقابية.",
  "user-activity": "يعرض نشاط المستخدمين في النظام مع تفاصيل الإجراءات المتخذة والموارد التي تم الوصول إليها، لمراقبة أداء المستخدمين.",

  // ── تقارير المستخدمين ──
  "user-list": "يعرض قائمة المستخدمين المسجلين في النظام مع أدوارهم وصلاحياتهم وحالتهم، لإدارة حسابات المستخدمين.",
  "user-performance": "يقيم أداء المستخدمين من خلال عدد الفواتير وإجمالي المبيعات ومتوسط الفاتورة والأخطاء المسجلة، لتقييم الإنتاجية.",
  "login-history": "يعرض سجل تسجيل دخول المستخدمين مع تاريخ ووقت الدخول والخروج وعنوان IP، للأغراض الأمنية والرقابية.",

  // ── تقارير المصروفات ──
  "expense-summary": "ملخص المصروفات خلال الفترة مع إجمالي المصروفات حسب الفئة، لمتابعة بنود الإنفاق.",
  "detailed-expenses": "يعرض جميع المصروفات بالتفصيل مع تاريخ الصرف والفئة والمبلغ وطريقة الدفع والبيان، لفحص كل مصروف.",
  "expenses-by-category": "يجمع المصروفات حسب فئاتها مع إجمالي كل فئة ونسبتها من الإجمالي، لتحليل توزيع الإنفاق.",
  "expenses-by-payment": "يوزع المصروفات حسب طرق الدفع (نقداً، بطاقة، تحويل) مع إجمالي المصروفات لكل طريقة.",

  // ── تقارير الإيرادات ──
  "revenue-summary": "ملخص الإيرادات الأخرى خلال الفترة مع إجمالي الإيرادات حسب الفئة، لمتابعة الإيرادات غير البيعية.",
  "detailed-revenues": "يعرض جميع الإيرادات الأخرى بالتفصيل مع تاريخ الإيراد والفئة والمبلغ وطريقة الدفع والبيان.",
  "revenues-by-category": "يجمع الإيرادات حسب فئاتها مع إجمالي كل فئة ونسبتها من الإجمالي، لتحليل مصادر الإيرادات.",
  "revenues-by-payment": "يوزع الإيرادات حسب طرق الدفع مع إجمالي الإيرادات لكل طريقة دفع.",

  // ── تقارير الشيكات والبنوك ──
  "cheque-listing": "يعرض كشف بجميع الشيكات المسجلة في النظام مع حالة كل شيك وتاريخه وقيمته والبنك والطرف، لمتابعة الشيكات.",
  "bank-transactions": "يعرض جميع حركات البنوك مع تفاصيل الإيداع والسحب والتاريخ والمرجع والرصيد، لكشوف الحساب البنكية.",
  "bank-summary": "ملخص أرصدة البنوك مع إجمالي الإيداعات والسحوبات والصافي لكل حساب بنكي.",

  // ── تقارير التقسيط ──
  "installment-plans": "يعرض خطط التقسيط النشطة مع تفاصيل المبلغ الإجمالي والمقدم وعدد الأقساط وقيمة القسط والرصيد المتبقي.",
  "installment-collections": "يعرض تحصيلات التقسيط مع تفاصيل القسط المستلم والتاريخ والعميل ورقم خطة التقسيط، لمتابعة الدفعات.",
  "installments-by-customer": "يعرض خطط التقسيط حسب العميل مع تفاصيل الأقساط المسددة والمستحقة والمتأخرة لكل خطة.",
  "installment-delinquent": "يكشف خطط التقسيط المتعثرة التي تجاوزت موعد استحقاق أقساطها مع إجمالي المتأخرات والأقساط المتأخرة.",

  // ── تقارير المخازن ──
  "branch-transfers": "يعرض حركات التحويل بين المخازن مع تاريخ التحويل والصنف والكمية والمخازن المرسلة والمستقبلة.",
  "warehouse-levels": "يعرض أرصدة المخازن التفصيلية لكل صنف في كل مخزن مع الكمية وتكلفة الوحدة.",
  "warehouse-levels-summary": "ملخص أرصدة المخازن مع إجمالي الأصناف والكميات والقيم لكل مخزن.",

  // ── تقارير الموظفين ──
  "employee-list": "يعرض جميع الموظفين المسجلين في النظام مع بياناتهم الأساسية (المسمى الوظيفي، الراتب، دورة الراتب) وإجمالي الخصومات والمكافآت والسلف النشطة، مع حالة كل موظف.",
  "employee-deductions": "يعرض جميع خصومات الموظفين مع تفاصيل النوع والمبلغ والحالة والتسلسل الزمني. يمكن التصفية حسب الموظف ونوع الخصم والحالة.",
  "employee-bonuses": "يعرض جميع مكافآت الموظفين مع تفاصيل النوع والمبلغ والحالة والتسلسل الزمني. يمكن التصفية حسب الموظف ونوع المكافأة والحالة.",
  "employee-advances": "يعرض جميع سلف الموظفين مع تفاصيل المبلغ والرصيد المتبقي والمبلغ المسدد وعدد الأقساط. يمكن التصفية حسب الموظف والحالة.",
  "employee-payroll": "يعرض كشوف رواتب الموظفين المسددة مع تفاصيل الراتب الأساسي وإجمالي الخصومات والمكافآت وصافي الراتب وطريقة الدفع.",
  "employee-full-history": "يعرض السجل المالي الكامل لكل موظف موحداً من جميع المصادر (الخصومات، المكافآت، السلف، دفعات السلف، صرف الرواتب) في جدول زمني واحد.",
  "employee-adjustments": "يعرض تسويات الموظفين (التعديلات اليدوية على الخصومات والمكافآت) مع تفاصيل النوع والمبلغ والتاريخ والمستخدم، لضبط حسابات الموظفين.",

  // ── تقارير الأرباح ──
  "profit-by-category": "يحلل الأرباح حسب فئات الأصناف مع إجمالي المبيعات والتكلفة والربح وهامش الربح لكل فئة.",
  "profit-by-customer": "يحلل الأرباح حسب العملاء مع إجمالي المشتريات والتكلفة والربح والنسبة لكل عميل، لتحديد العملاء الأكثر ربحية.",
  "profit-by-period": "يقارن الأرباح عبر فترات زمنية متتالية مع إجمالي المبيعات والتكلفة والربح الشهري أو الأسبوعي.",
};

const REPORT_TITLES = {
  "daily-sales": "الملخص اليومي للمبيعات",
  "detailed-sales": "المبيعات التفصيلية",
  "sales-by-item": "مبيعات حسب الصنف",
  "sales-by-category": "مبيعات حسب الفئة",
  "sales-by-cashier": "مبيعات حسب الكاشير",
  "sales-by-payment": "مبيعات حسب طريقة الدفع",
  "sales-heatmap": "خريطة كثافة المبيعات",
  "exceptions": "استثناءات المبيعات",
  "period-comparison": "مقارنة الفترات",
  "slow-moving": "الأصناف بطيئة الحركة",
  "stock-levels": "أرصدة المخزون",
  "stock-movements": "حركات المخزون",
  "stock-valuation": "تقييم المخزون",
  "count-sheet": "كشف الجرد",
  "reorder": "إعادة الطلب",
  "expiry": "تواريخ الصلاحية",
  "profit-loss": "الأرباح والخسائر",
  "cash-flow": "التدفق النقدي",
  "treasury": "الخزائن والبنوك",
  "vat": "ضريبة القيمة المضافة",
  "customer-statement": "كشف حساب عميل",
  "shift-history": "سجل الورديات",
  "audit-log": "سجل التدقيق",
  "gross-net-sales": "إجمالي وصافي المبيعات",
  "sales-returns": "مرتجعات المبيعات",
  "discount-analysis": "تحليل الخصومات",
  "margin-by-item": "هامش الربح حسب الصنف",
  "margin-by-category": "هامش الربح حسب الفئة",
  "purchase-summary": "ملخص المشتريات",
  "detailed-purchases": "المشتريات التفصيلية",
  "purchases-by-supplier": "مشتريات حسب المورد",
  "purchases-by-item": "مشتريات حسب الصنف",
  "purchase-returns": "مرتجعات المشتريات",
  "supplier-pricing": "أسعار الموردين",
  "inventory-aging": "أعمار المخزون",
  "dead-stock": "المخزون الراكد",
  "supplier-statement": "كشف حساب مورد",
  "cash-consistency": "مطابقة النقدية",
  "payment-method-flow": "تدفق وسائل الدفع",
  "payment-flow-summary": "ملخص تدفقات وسائل الدفع",
  "payment-flow-ledger": "سجل تدفقات وسائل الدفع التفصيلي",
  "payment-flow-by-doc-type": "تدفقات وسائل الدفع حسب نوع المستند",
  "payment-flow-by-direction": "تدفقات وسائل الدفع حسب الاتجاه",
  "payment-flow-running": "الرصيد التراكمي لوسائل الدفع",
  "bank-cash-split": "توزيع الخزائن والبنوك",
  "reconciliation-exceptions": "استثناءات التسوية",
  "output-vat": "ضريبة المخرجات",
  "input-vat": "ضريبة المدخلات",
  "vat-filing-summary": "ملخص الإقرار الضريبي",
  "returns-tax-effect": "الأثر الضريبي للمرتجعات",
  "user-activity": "نشاط المستخدمين",
  "margin-health": "صحة هوامش الربح",
  "sales-returns-summary": "ملخص مرتجعات المبيعات",
  "sales-returns-by-customer": "مرتجعات المبيعات حسب العميل",
  "purchase-returns-summary": "ملخص مرتجعات المشتريات",
  "purchase-returns-by-supplier": "مرتجعات المشتريات حسب المورد",
  "daily-sessions": "جلسات الخزينة اليومية",
  "withdrawals-report": "تقرير السحوبات",
  "expense-summary": "ملخص المصروفات",
  "detailed-expenses": "المصروفات التفصيلية",
  "expenses-by-category": "المصروفات حسب الفئة",
  "expenses-by-payment": "المصروفات حسب طريقة الدفع",
  "revenue-summary": "ملخص الإيرادات",
  "detailed-revenues": "الإيرادات التفصيلية",
  "revenues-by-category": "الإيرادات حسب الفئة",
  "revenues-by-payment": "الإيرادات حسب طريقة الدفع",
  "cheque-listing": "كشف الشيكات",
  "bank-transactions": "حركات البنوك",
  "bank-summary": "ملخص البنوك",
  "installment-plans": "خطط التقسيط",
  "installment-collections": "تحصيلات التقسيط",
  "installments-by-customer": "التقسيط حسب العميل",
  "installment-delinquent": "المتأخرات التقسيط",
  "branch-transfers": "التحويلات بين الفروع",
  "warehouse-levels": "أرصدة المخازن",
  "warehouse-levels-summary": "ملخص أرصدة المخازن",
  "employee-adjustments": "تسويات الموظفين",
  "user-list": "قائمة المستخدمين",
  "user-performance": "أداء المستخدمين",
  "login-history": "سجل تسجيل الدخول",
  "profit-by-category": "الربح حسب الفئة",
  "profit-by-customer": "الربح حسب العميل",
  "profit-by-period": "الربح حسب الفترة",
  "cost-movements": "تقرير حركات التكلفة",
  "cost-method-comparison": "مقارنة طرق التكلفة",
  "item-lifecycle": "دورة حياة الصنف",
  "margin-drift": "تغير الهامش والتكلفة",
  "inventory-turnover": "دوران المخزون وأيام التغطية",
  "cashier-override-impact": "أثر تجاوزات الكاشير",
  "stock-adjustment-audit": "تدقيق تسويات المخزون",
  "daily-owner-snapshot": "لقطة صاحب المحل اليومية",
  "ar-aging": "تقادم ذمم العملاء",
  "ap-aging": "تقادم ذمم الموردين",
  "top-customers": "أفضل العملاء",
  "collection-efficiency": "كفاءة التحصيل",
  "customer-loyalty": "ولاء العملاء",
  "supplier-reliability": "موثوقية الموردين",
  "customer-balance-list": "قائمة أرصدة العملاء",
  "supplier-balance-list": "قائمة أرصدة الموردين",
  "employee-list": "قائمة الموظفين",
  "employee-deductions": "خصومات الموظفين",
  "employee-bonuses": "مكافآت الموظفين",
  "employee-advances": "سلف الموظفين",
  "employee-payroll": "كشوف رواتب الموظفين",
  "employee-full-history": "السجل الكامل للموظف",
};

const AR_LABELS = {
  id: "المعرف",
  item_code: "كود الصنف",
  code: "الكود",
  sku: "SKU",
  barcode: "الباركود",
  item_id: "معرف الصنف",
  item_name: "اسم الصنف",
  name: "الاسم",
  invoice_no: "رقم الفاتورة",
  doc_no: "رقم المستند",
  purchase_no: "رقم الشراء",
  ref_no: "رقم المرجع",
  return_ref: "رقم المرتجع",
  customer_name: "العميل",
  supplier_name: "المورد",
  cashier: "الكاشير",
  handled_by: "تم بواسطة",
  created_by: "أنشئ بواسطة",
  full_name: "المستخدم",
  phone: "الهاتف",
  date: "التاريخ",
  created_at: "تاريخ الإنشاء",
  opened_date: "تاريخ الفتح",
  closed_at: "تاريخ الإغلاق",
  purchase_date: "تاريخ الشراء",
  last_purchase_date: "آخر تاريخ شراء",
  last_invoice_date: "آخر فاتورة",
  last_sale_date: "آخر بيع",
  last_movement_date: "آخر حركة",
  expiry_date: "تاريخ الصلاحية",
  total: "الإجمالي",
  subtotal: "قبل الخصم",
  gross_sales: "إجمالي المبيعات",
  net_sales: "صافي المبيعات",
  sales_total: "إجمالي المبيعات",
  total_sales: "إجمالي المبيعات",
  total_purchases: "إجمالي المشتريات",
  purchases_total: "إجمالي المشتريات",
  total_spent: "إجمالي الإنفاق",
  total_amount: "إجمالي المبلغ",
  total_billed: "إجمالي الفواتير",
  total_due: "إجمالي المستحق",
  total_cost: "إجمالي التكلفة",
  line_total: "إجمالي السطر",
  total_value: "إجمالي القيمة",
  total_value_wacc: "القيمة بمتوسط التكلفة",
  total_value_last_purchase: "القيمة بآخر شراء",
  total_discount: "إجمالي الخصم",
  discount_total: "إجمالي الخصم",
  discount: "الخصم",
  avg_discount: "متوسط الخصم",
  avg_discount_percent: "متوسط الخصم %",
  discount_range: "نطاق الخصم",
  return_discount: "خصم المرتجع",
  return_increase: "زيادة المرتجع",
  return_total: "صافي المرتجع",
  returns_total: "إجمالي المرتجعات",
  returns_amount: "قيمة المرتجعات",
  return_amount: "قيمة المرتجع",
  vat_reversed: "الضريبة المستردة",
  revenue: "الإيراد",
  cost: "التكلفة",
  cost_price: "سعر التكلفة",
  unit_price: "سعر الوحدة",
  unit_cost: "تكلفة الوحدة",
  wacc: "متوسط التكلفة",
  last_purchase_cost: "آخر تكلفة شراء",
  avg_unit_cost: "متوسط تكلفة الوحدة",
  avg_unit_price: "متوسط سعر الوحدة",
  sale_price: "سعر البيع",
  purchase_price: "سعر الشراء",
  gross_profit: "مجمل الربح",
  profit_margin: "هامش الربح",
  margin_percent: "هامش الربح %",
  current_margin_percent: "الهامش الحالي %",
  min_margin_percent: "الحد الأدنى %",
  suggested_price: "السعر المقترح",
  below_threshold: "تحت الحد",
  quantity: "الكمية",
  quantity_sold: "الكمية المباعة",
  quantity_purchased: "الكمية المشتراة",
  stock_quantity: "رصيد المخزون",
  system_quantity: "رصيد النظام",
  total_quantity: "إجمالي الكمية",
  before_qty: "الرصيد قبل",
  after_qty: "الرصيد بعد",
  min_stock_qty: "حد أدنى للمخزون",
  unit_name: "الوحدة",
  item_count: "عدد الأصناف",
  invoice_count: "عدد الفواتير",
  purchase_count: "عدد المشتريات",
  return_count: "عدد المرتجعات",
  returns_count: "عدد المرتجعات",
  cancelled_count: "الفواتير الملغاة",
  returns_handled: "المرتجعات المعالجة",
  items_returned: "الأصناف المرتجعة",
  transaction_count: "عدد المعاملات",
  action_count: "عدد العمليات",
  total_invoices: "عدد الفواتير",
  total_items_sold: "عدد الأصناف المباعة",
  distinct_suppliers: "عدد الموردين",
  supplier_count: "عدد الموردين",
  customer_count: "عدد العملاء",
  category_name: "الفئة",
  payment_type: "طريقة الدفع",
  status: "الحالة",
  type: "النوع",
  source: "المصدر",
  movement_type: "نوع الحركة",
  reference_type: "نوع المرجع",
  reference_id: "رقم المرجع",
  resource: "المورد",
  action: "الإجراء",
  payload_json: "التفاصيل",
  user_id: "المستخدم",
  warehouse_id: "المخزن",
  balance: "الرصيد",
  balance_label: "الاتجاه",
  opening_balance: "الرصيد الافتتاحي",
  closing_balance: "الرصيد الختامي",
  running_balance: "الرصيد الجاري",
  debit: "مدين",
  credit: "دائن",
  opening_cash: "النقدية الافتتاحية",
  closing_cash: "النقدية الختامية",
  expected_cash: "النقدية المتوقعة",
  cash_variance: "فرق النقدية",
  variance: "الفرق",
  collected: "المحصل",
  outstanding: "المستحق",
  collection_rate: "نسبة التحصيل %",
  days_to_collect: "أيام التحصيل",
  aging_0_30: "0-30 يوم",
  aging_31_60: "31-60 يوم",
  aging_61_90: "61-90 يوم",
  aging_90_plus: "أكثر من 90 يوم",
  days_until_expiry: "أيام حتى الصلاحية",
  days_since_last_movement: "أيام منذ آخر حركة",
  days_since_last_sale: "أيام منذ آخر بيع",
  aging_bucket: "فئة العمر",
  stock_status: "حالة المخزون",
  expiry_status: "حالة الصلاحية",
  tax_rate: "نسبة الضريبة",
  taxable_sales: "المبيعات الخاضعة",
  taxable_amount: "المبلغ الخاضع",
  vat_amount: "قيمة الضريبة",
  output_vat: "ضريبة المخرجات",
  input_vat: "ضريبة المدخلات",
  net_vat: "صافي الضريبة",
  amount: "المبلغ",
  pct: "النسبة %",
  section: "البند",
  label: "البيان",
  period: "الفترة",
  hour_slot: "الساعة",
  weekday: "يوم الأسبوع",
  weekday_name: "يوم الأسبوع",
  weekday_num: "رقم اليوم",
  avg_sale: "متوسط البيع",
  avg_transaction: "متوسط المعاملة",
  avg_invoice_value: "متوسط الفاتورة",
  avg_order_value: "متوسط الطلب",
  payment_method: "وسيلة الدفع",
  method_id: "معرف وسيلة الدفع",
  method_name: "وسيلة الدفع",
  method_category: "تصنيف الوسيلة",
  method_type: "نوع الوسيلة",
  method_icon: "رمز الوسيلة",
  excludes_from_treasury: "خارج الخزينة",
  total_in: "إجمالي الداخل",
  total_out: "إجمالي الخارج",
  net_amount: "الصافي",
  signed_amount: "التأثير",
  last_movement_at: "آخر حركة",
  direction: "الاتجاه",
  direction_label: "الاتجاه",
  doc_type: "نوع المستند",
  doc_type_label: "نوع المستند",
  source_group: "المصدر",
  party_type: "نوع الطرف",
  party: "الطرف",
  raw_method: "كود الوسيلة",
  refund_method: "وسيلة الاسترداد",
  reason: "السبب",
  exception_type: "نوع الاستثناء",
  shift_id: "رقم الوردية",
  tx_count: "عدد الحركات",
  percentage: "النسبة %",
  running_total: "الإجمالي التراكمي",
  batch_no: "رقم الدفعة",
  potential_revenue: "إيراد محتمل",
  suggested_order_qty: "كمية الطلب المقترحة",
  estimated_order_cost: "تكلفة الطلب المقدرة",
  preferred_supplier: "المورد المفضل",
  loyalty_points: "نقاط الولاء",
  loyalty_tier: "شريحة الولاء",
  // ── Additional labels from actual SQL output ──
  gross_profit: "إجمالي الربح",
  total_gross_profit: "إجمالي الربح الإجمالي",
  gross_sales: "إجمالي المبيعات",
  net_sales: "صافي المبيعات",
  sales_total: "إجمالي المبيعات",
  avg_invoice_value: "متوسط قيمة الفاتورة",
  avg_transaction: "متوسط المعاملة",
  avg_order_value: "متوسط الطلب",
  avg_sale: "متوسط البيع",
  avg_discount: "متوسط الخصم",
  avg_unit_cost: "متوسط تكلفة الوحدة",
  avg_unit_price: "متوسط سعر الوحدة",
  running_balance: "الرصيد الجاري",
  opening_balance: "الرصيد الافتتاحي",
  closing_balance: "الرصيد الختامي",
  expected_cash: "النقدية المتوقعة",
  cash_variance: "فرق النقدية",
  opening_cash: "النقدية الافتتاحية",
  closing_cash: "النقدية الختامية",
  distinct_suppliers: "عدد الموردين المميزين",
  potential_revenue: "الإيراد المحتمل",
  suggested_order_qty: "كمية الطلب المقترحة",
  estimated_order_cost: "تكلفة الطلب المقدرة",
  preferred_supplier: "المورد المفضل",
  returns_handled: "المرتجعات المعالجة",
  items_returned: "الأصناف المرتجعة",
  payment_method: "وسيلة الدفع",
  refund_method: "وسيلة الاسترداد",
  exception_type: "نوع الاستثناء",
  tx_count: "عدد الحركات",
  percentage: "النسبة المئوية",
  running_total: "الإجمالي التراكمي",
  batch_no: "رقم الدفعة",
  opening_balance: "الرصيد الافتتاحي",
  net_vat: "صافي الضريبة",
  total_value: "القيمة الإجمالية",
  total_value_wacc: "القيمة (متوسط التكلفة)",
  total_value_last_purchase: "القيمة (آخر سعر شراء)",
  total_billed: "إجمالي الفواتير",
  total_due: "إجمالي المستحق",
  line_total: "إجمالي السطر",
  unit_price: "سعر الوحدة",
  unit_cost: "تكلفة الوحدة",
  sale_price: "سعر البيع",
  purchase_price: "سعر الشراء",
  current_margin_percent: "الهامش الحالي %",
  min_margin_percent: "الحد الأدنى للهامش %",
  suggested_price: "السعر المقترح",
  below_threshold: "تحت الحد الأدنى",
  stock_status: "حالة المخزون",
  expiry_status: "حالة الصلاحية",
  taxable_sales: "المبيعات الخاضعة للضريبة",
  taxable_amount: "المبلغ الخاضع للضريبة",
  vat_amount: "قيمة الضريبة",
  output_vat: "ضريبة المخرجات",
  input_vat: "ضريبة المدخلات",
  last_purchase_cost: "آخر تكلفة شراء",
  wacc: "متوسط التكلفة المرجح",
  profit_margin: "هامش الربح",
  margin_percent: "نسبة هامش الربح",
  item_name: "اسم الصنف",
  category_name: "اسم الفئة",
  customer_name: "اسم العميل",
  supplier_name: "اسم المورد",
  unit_name: "اسم الوحدة",
  weekday_name: "اسم اليوم",
  full_name: "الاسم الكامل",
  username: "اسم المستخدم",
  role: "الصلاحية",
  admin: "مدير",
  cashier: "كاشير",
  manager: "مشرف",
  status: "الحالة",
  last_login: "آخر تسجيل دخول",
  shift_count: "عدد الورديات",
  details: "التفاصيل",
  phone: "رقم الهاتف",
  invoice_no: "رقم الفاتورة",
  doc_no: "رقم المستند",
  purchase_no: "رقم المشتريات",
  ref_no: "رقم المرجع",
  return_ref: "رقم المرتجع",
  warehouse_id: "المخزن",
  cashier: "الكاشير",
  handled_by: "تم بواسطة",
  created_by: "أنشئ بواسطة",
  user_id: "المستخدم",
  action: "الإجراء",
  resource: "المورد",
  payload_json: "التفاصيل",
  movement_type: "نوع الحركة",
  reference_type: "نوع المرجع",
  reference_id: "رقم المرجع",
  before_qty: "الرصيد قبل",
  after_qty: "الرصيد بعد",
  min_stock_qty: "الحد الأدنى للكمية",
  stock_quantity: "كمية المخزون",
  system_quantity: "كمية النظام",
  total_quantity: "إجمالي الكمية",
  quantity_sold: "الكمية المباعة",
  quantity_purchased: "الكمية المشتراة",
  invoice_count: "عدد الفواتير",
  purchase_count: "عدد المشتريات",
  return_count: "عدد المرتجعات",
  returns_count: "عدد المرتجعات",
  cancelled_count: "عدد الملغاة",
  item_count: "عدد الأصناف",
  transaction_count: "عدد المعاملات",
  action_count: "عدد العمليات",
  total_invoices: "إجمالي الفواتير",
  total_items_sold: "إجمالي الأصناف المباعة",
  supplier_count: "عدد الموردين",
  customer_count: "عدد العملاء",
  days_until_expiry: "الأيام حتى الصلاحية",
  days_since_last_movement: "أيام منذ آخر حركة",
  days_since_last_sale: "أيام منذ آخر بيع",
  days_to_collect: "أيام التحصيل",
  aging_0_30: "0-30 يوم",
  aging_31_60: "31-60 يوم",
  aging_61_90: "61-90 يوم",
  aging_90_plus: "أكثر من 90 يوم",
  aging_bucket: "فئة العمر",
  collected: "المحصل",
  outstanding: "المستحق",
  collection_rate: "نسبة التحصيل",
  last_sale_date: "آخر تاريخ بيع",
  last_purchase_date: "آخر تاريخ شراء",
  last_invoice_date: "آخر تاريخ فاتورة",
  last_movement_date: "آخر تاريخ حركة",
  expiry_date: "تاريخ الصلاحية",
  // ── Previously-unmapped keys (were rendering as raw English) ──
  account_no: "رقم الحساب",
  adjustment_type: "نوع التسوية",
  available_balance: "الرصيد المتاح",
  avg_daily_sales: "متوسط المبيعات اليومية",
  avg_diff_pct: "متوسط الفرق %",
  avg_discount_pct: "متوسط الخصم %",
  avg_payment_days: "متوسط أيام السداد",
  avg_price_spread_percent: "متوسط تشتت السعر %",
  bank_name: "اسم البنك",
  category_count: "عدد الفئات",
  cheque_no: "رقم الشيك",
  cogs: "تكلفة البضاعة المباعة",
  cost_basis: "أساس التكلفة",
  cost_change: "تغيّر التكلفة",
  current_cost: "التكلفة الحالية",
  current_wacc: "متوسط التكلفة الحالي",
  days_of_stock: "أيام تغطية المخزون",
  days_overdue: "أيام التأخير",
  days_since_last_purchase: "أيام منذ آخر شراء",
  description: "الوصف",
  discount_invoice_count: "عدد فواتير الخصم",
  due_date: "تاريخ الاستحقاق",
  employee_name: "اسم الموظف",
  estimated_revenue_impact: "الأثر التقديري على الإيراد",
  expense_count: "عدد المصروفات",
  expenses: "المصروفات",
  first_period_cost: "تكلفة الفترة الأولى",
  from_warehouse: "من مخزن",
  gross_revenue: "إجمالي الإيراد",
  gross_spent: "إجمالي الإنفاق",
  installment_count: "عدد الأقساط",
  installment_no: "رقم القسط",
  inventory_value: "قيمة المخزون",
  last_period_cost: "تكلفة الفترة الأخيرة",
  last_return_date: "آخر تاريخ مرتجع",
  lifetime_gross_profit: "إجمالي الربح التراكمي",
  low_stock_alerts_count: "عدد تنبيهات نقص المخزون",
  margin_decline_percent: "نسبة تراجع الهامش %",
  net_profit: "صافي الربح",
  net_quantity_purchased: "صافي الكمية المشتراة",
  net_revenue: "صافي الإيراد",
  net_total_cost: "صافي إجمالي التكلفة",
  other_revenues: "إيرادات أخرى",
  overdue: "المتأخر",
  overdue_amount: "المبلغ المتأخر",
  overdue_count: "عدد المتأخرات",
  overdue_receivables_count: "عدد الذمم المتأخرة",
  override_count: "عدد التعديلات",
  paid_amount: "المبلغ المدفوع",
  payee_name: "المستفيد",
  period_end: "نهاية الفترة",
  period_start: "بداية الفترة",
  plan_id: "رقم الخطة",
  previous_margin_percent: "الهامش السابق %",
  price_downs: "تخفيضات السعر",
  price_ups: "زيادات السعر",
  purchase_qty: "كمية الشراء",
  purchase_return_value: "قيمة مرتجع الشراء",
  purchase_value: "قيمة الشراء",
  qty_change: "تغيّر الكمية",
  qty_sold: "الكمية المباعة",
  quantity_returned: "الكمية المرتجعة",
  reference_no: "رقم المرجع",
  repeat_items: "الأصناف المتكررة",
  return_rate_percent: "نسبة المرتجعات %",
  returns_cost: "تكلفة المرتجعات",
  revenue_count: "عدد الإيرادات",
  running_quantity: "الكمية التراكمية",
  running_wacc: "متوسط التكلفة التراكمي",
  sales_cost: "تكلفة المبيعات",
  sales_qty: "كمية المبيعات",
  sales_return_value: "قيمة مرتجع المبيعات",
  sales_revenue: "إيراد المبيعات",
  source_doc_no: "رقم المستند المصدر",
  source_table: "المصدر",
  spread_min_max: "الفارق بين الأدنى والأعلى",
  start_date: "تاريخ البداية",
  stock_on_hand: "الرصيد المتاح",
  stock_velocity_status: "حالة دوران المخزون",
  to_warehouse: "إلى مخزن",
  total_expenses: "إجمالي المصروفات",
  total_header_discount: "إجمالي خصم الفاتورة",
  total_plans: "عدد الخطط",
  total_returns: "إجمالي المرتجعات",
  total_revenue: "إجمالي الإيراد",
  total_transactions: "عدد المعاملات",
  transfer_no: "رقم التحويل",
  treasury_name: "اسم الخزينة",
  turnover_ratio: "معدل الدوران",
  value_fifo: "القيمة (الوارد أولاً)",
  value_impact: "الأثر على القيمة",
  value_last: "القيمة (آخر تكلفة)",
  value_lifo: "القيمة (الوارد أخيراً)",
  value_wacc: "القيمة (متوسط التكلفة)",
  warehouse: "المخزن",
  warehouse_name: "المخزن",
  withdrawals: "المسحوبات",
  // ── Additional SQL aliases surfaced by specific queries ──
  avg_cost: "متوسط التكلفة",
  avg_expense: "متوسط المصروف",
  avg_revenue: "متوسط الإيراد",
  cashier_id: "الكاشير",
  cost_of_goods_sold: "تكلفة البضاعة المباعة",
  created_date: "تاريخ الإنشاء",
  customer_id: "العميل",
  debt_date: "تاريخ الدين",
  debt_total: "إجمالي الدين",
  discounts: "الخصومات",
  distinct_customers: "عدد العملاء",
  first_purchase_date: "أول تاريخ شراء",
  first_sale_date: "أول تاريخ بيع",
  last_cost: "آخر تكلفة",
  last_due_date: "آخر تاريخ استحقاق",
  last_expense_date: "آخر تاريخ مصروف",
  line_cost: "تكلفة السطر",
  line_discount: "خصم السطر",
  line_profit: "ربح السطر",
  low_stock_items: "أصناف تحت الحد",
  max_cost: "أعلى تكلفة",
  min_cost: "أدنى تكلفة",
  on_hand: "المتاح",
  outstanding_amount: "المبلغ المستحق",
  overdue_bucket: "فئة التأخير",
  paid_count: "عدد المدفوعات",
  party_id: "الطرف",
  party_type: "نوع الطرف",
  payment_breakdown: "تفاصيل الدفع",
  pending_count: "عدد المعلّقة",
  plan_count: "عدد الخطط",
  purchase_id: "رقم الشراء",
  purchase_return_qty: "كمية مرتجع الشراء",
  purchase_return_tx_count: "عدد معاملات مرتجع الشراء",
  purchase_tx_count: "عدد معاملات الشراء",
  remaining_pct: "نسبة المتبقي %",
  return_cost: "تكلفة المرتجع",
  return_revenue: "إيراد المرتجع",
  sales_return_qty: "كمية مرتجع المبيعات",
  sales_return_tx_count: "عدد معاملات مرتجع المبيعات",
  sales_tx_count: "عدد معاملات المبيعات",
  supplier_id: "المورد",
  total_deposits: "إجمالي الإيداعات",
  total_paid: "إجمالي المدفوع",
  total_remaining: "إجمالي المتبقي",
  total_revenues: "إجمالي الإيرادات",
  total_withdrawals: "إجمالي المسحوبات",
  transfer_in_qty: "الوارد (تحويل)",
  transfer_out_qty: "الصادر (تحويل)",
  transfer_tx_count: "عدد التحويلات",
  // ── Reconciliation columns: gross selling price + additions/fees ──
  selling_total: "إجمالي سعر البيع",
  additions_amount: "إضافة / رسوم",
  // ── Misc labels surfaced after the column-catalog re-sync ──
  reference: "المرجع",
  notes: "ملاحظات",
  drawer_name: "الساحب",
  min_stock: "الحد الأدنى للمخزون",
  remaining: "المتبقي",
  down_payment: "الدفعة المقدمة",
  frequency: "التكرار",
  installment_amount: "قيمة القسط",
  paid_at: "تاريخ السداد",
  net_purchases: "صافي المشتريات",
  potential_profit: "ربح محتمل",
  items_per_invoice: "أصناف لكل فاتورة",
  pct_of_sales: "نسبة من المبيعات %",
  pct_of_total: "النسبة من الإجمالي %",
  value_share_pct: "نسبة من قيمة المخزون %",
  avg_return_value: "متوسط قيمة المرتجع",
  net_flow: "صافي التدفق",
  frequency_monthly: "معدل الشراء شهرياً",
  days_since_last_purchase: "أيام منذ آخر شراء",
  first_invoice_date: "أول تاريخ شراء",
  last_collection_date: "آخر تاريخ تحصيل",
  partially_paid_count: "عدد المسدد جزئياً",
  fully_paid_count: "عدد المسدد بالكامل",
  total_sales: "إجمالي المبيعات",
  net_sales: "صافي المبيعات",
  return_rate_percent: "نسبة المرتجعات %",
  avg_payment_days: "متوسط أيام السداد",
  repeat_items: "الأصناف المتكررة",
  avg_price_spread_percent: "تشتت الأسعار %",
  overdue_amount: "المبلغ المتأخر",
  collection_rate: "نسبة التحصيل %",
  days_to_collect: "أيام التحصيل",
  total_billed: "إجمالي الفواتير",
  items_per_invoice: "أصناف لكل فاتورة",
  avg_discount_percent: "متوسط الخصم %",
  margin_percent: "هامش الربح %",
  gross_profit: "مجمل الربح",
  total_cost: "إجمالي التكلفة",
  returns_total: "إجمالي المرتجعات",
  invoice_count: "عدد الفواتير",
  purchase_count: "عدد المشتريات",
  // ── SQL aliases & columns missing from original AR_LABELS ──
  buys: "مشتريات",
  datetime: "التاريخ والوقت",
  doc_discount: "خصم المستند",
  doc_id: "رقم المستند",
  doc_increase: "إضافة المستند",
  doc_total: "إجمالي المستند",
  employee_id: "الموظف",
  line_sum: "مجموع البنود",
  net_total: "صافي الإجمالي",
  occurred_at: "تاريخ الحدوث",
  orig_ref: "المرجع الأصلي",
  ref_id: "رقم المرجع",
  source_id: "المصدر",
  source_line_id: "رقم سطر المصدر",
  tax_amount: "مبلغ الضريبة",
  tax_type: "نوع الضريبة",
  tax_type_label: "نوع الضريبة",
  status_label: "الحالة",
  period_label: "الفترة",
  basis_label: "أساس الحساب",
  method_name: "وسيلة الدفع",
  plan_id: "رقم الخطة",
  total_tax: "إجمالي الضريبة",
  updated_at: "آخر تحديث",
  v: "القيمة",
  // ── Employee report labels ──
  job_title: "المسمى الوظيفي",
  salary: "الراتب",
  salary_period: "دورة الراتب",
  working_days_per_month: "أيام العمل الشهرية",
  daily_salary: "الراتب اليومي",
  active_deductions_total: "إجمالي الخصومات",
  active_bonuses_total: "إجمالي المكافآت",
  active_advances_balance: "رصيد السلف",
  deduction_type: "نوع الخصم",
  deduction_type_label: "نوع الخصم",
  bonus_type: "نوع المكافأة",
  bonus_type_label: "نوع المكافأة",
  recurring_label: "متكرر",
  is_recurring: "متكرر",
  completed_at: "تاريخ التطبيق",
  cancelled_at: "تاريخ الإلغاء",
  remaining_balance: "الرصيد المتبقي",
  repaid_amount: "المبلغ المسدد",
  base_salary: "الراتب الأساسي",
  total_bonuses: "إجمالي المكافآت",
  total_deductions: "إجمالي الخصومات",
  advance_deductions: "خصم السلف",
  net_salary: "صافي الراتب",
  settled_at: "تاريخ الصرف",
  settled_by: "تم الصرف بواسطة",
  expense_id: "رقم المصروف",
  tx_type: "نوع الحركة",
  tx_type_label: "نوع الحركة",
  sub_type: "النوع الفرعي",
};

// Short Arabic help text shown next to each report column (e.g. in a column-picker
// tooltip). Covers every key used across REPORT_COLUMN_KEYS. For computed money/percent
// columns the sentence explains HOW the value is calculated, matched against the actual
// SQL in server/src/reports/queries/*.js and server/src/services/paymentFlowService.js.
const COLUMN_DESCRIPTIONS = {
  action: "نوع العملية التي نفّذها المستخدم في النظام (إضافة، تعديل، حذف، تسجيل دخول...).",
  action_count: "عدد مرات تنفيذ هذا الإجراء خلال الفترة.",
  active_advances_balance: "إجمالي الرصيد المتبقي على السلف النشطة لهذا الموظف.",
  active_bonuses_total: "إجمالي قيمة المكافآت النشطة التي لم تُصرف بعد لهذا الموظف.",
  active_deductions_total: "إجمالي قيمة الخصومات النشطة التي لم تُطبق بعد على هذا الموظف.",
  additions_amount: "قيمة الإضافات أو الرسوم المضافة على الفاتورة بعد الخصم.",
  adjustment_type: "نوع التسوية اليدوية المطبقة على حساب الموظف.",
  advance_deductions: "المبلغ المخصوم من الراتب سداداً لسلفة سابقة.",
  after_qty: "رصيد الصنف بعد تنفيذ الحركة أو التسوية.",
  aging_0_30: "المبالغ المستحقة التي مضى عليها 30 يوماً أو أقل.",
  aging_31_60: "المبالغ المستحقة التي مضى عليها من 31 إلى 60 يوماً.",
  aging_61_90: "المبالغ المستحقة التي مضى عليها من 61 إلى 90 يوماً.",
  aging_90_plus: "المبالغ المستحقة التي مضى عليها أكثر من 90 يوماً.",
  aging_bucket: "الفئة الزمنية التي يصنَّف ضمنها عمر الصنف في المخزون حسب مدة بقائه دون حركة أو دون بيع.",
  amount: "قيمة المبلغ في هذه الحركة.",
  avg_daily_sales: "متوسط الكمية المباعة من الصنف يومياً خلال فترة التقرير.",
  avg_diff_pct: "متوسط نسبة الفرق بين السعر الذي عدّله الكاشير والسعر الأصلي للصنف.",
  avg_discount: "متوسط قيمة الخصم لكل فاتورة (إجمالي الخصم ÷ عدد الفواتير).",
  avg_discount_pct: "متوسط نسبة الخصم إلى إجمالي الفاتورة.",
  avg_discount_percent: "متوسط نسبة الخصم إلى إجمالي الفاتورة قبل الخصم لهذا العميل.",
  avg_expense: "متوسط قيمة المصروف الواحد خلال الفترة (إجمالي المصروفات ÷ عددها).",
  avg_invoice_value: "متوسط قيمة الفاتورة الواحدة (إجمالي المبيعات ÷ عدد الفواتير).",
  avg_order_value: "متوسط قيمة فاتورة الشراء الواحدة (إجمالي المشتريات ÷ عدد الفواتير).",
  avg_payment_days: "متوسط عدد الأيام الفاصلة بين تاريخ فاتورة الشراء وتاريخ سدادها لهذا المورد.",
  avg_price_spread_percent: "متوسط نسبة التفاوت بين أعلى وأقل سعر اشتُري به نفس الصنف من هذا المورد ((أعلى سعر - أقل سعر) ÷ متوسط السعر × 100).",
  avg_return_value: "متوسط قيمة المرتجع الواحد (إجمالي المرتجعات ÷ عددها).",
  avg_revenue: "متوسط قيمة الإيراد الواحد خلال الفترة.",
  avg_sale: "متوسط قيمة عملية البيع الواحدة.",
  avg_transaction: "متوسط قيمة المعاملة الواحدة.",
  avg_unit_cost: "متوسط تكلفة الوحدة المباعة أو المشتراة من الصنف.",
  avg_unit_price: "متوسط سعر بيع الوحدة من الصنف.",
  balance: "الرصيد الحالي للحساب: موجب إذا كان الطرف مديناً (مستحق عليه)، وسالب أو معكوس إذا كان دائناً (مستحق له).",
  balance_label: "يوضح ما إذا كان الرصيد مديناً (عليه) أم دائناً (له).",
  bank_name: "اسم البنك المرتبط بهذه الحركة أو الشيك.",
  barcode: "الباركود الخاص بالصنف.",
  base_salary: "الراتب الأساسي للموظف قبل إضافة المكافآت أو خصم الاستقطاعات.",
  basis_label: "الأساس المستخدم في تجميع الإقرار الضريبي (نقدي أو استحقاقي).",
  batch_no: "رقم دفعة الصنف المرتبط بتاريخ صلاحية محدد.",
  before_qty: "رصيد الصنف قبل تنفيذ الحركة أو التسوية.",
  below_threshold: "يشير إلى أن هامش ربح الصنف الحالي أقل من الحد الأدنى المحدد له.",
  bonus_type: "كود نوع المكافأة.",
  bonus_type_label: "نوع المكافأة الممنوحة للموظف.",
  cancelled_at: "تاريخ إلغاء هذا الخصم أو المكافأة قبل تطبيقه.",
  cancelled_count: "عدد الفواتير التي تم إلغاؤها.",
  cash_variance: "الفرق بين النقدية الفعلية عند إغلاق الوردية والنقدية المتوقعة حسابياً (النقدية الافتتاحية + مبيعات الوردية النقدية).",
  cashier: "اسم الكاشير الذي نفّذ العملية.",
  cashier_id: "معرف الكاشير.",
  category_count: "عدد فئات الأصناف المختلفة.",
  category_name: "اسم فئة الصنف.",
  cheque_no: "رقم الشيك.",
  closed_at: "تاريخ ووقت إغلاق الوردية.",
  closing_cash: "قيمة النقدية الفعلية التي تم عدّها عند إغلاق الوردية.",
  code: "الكود الخاص بالسجل.",
  cogs: "تكلفة البضاعة المباعة (الكمية المباعة × تكلفة الوحدة).",
  collected: "إجمالي المبالغ التي تم تحصيلها فعلياً من العميل.",
  collection_rate: "نسبة المبلغ المحصَّل إلى إجمالي المبلغ المستحق (المحصَّل ÷ المستحق × 100).",
  completed_at: "تاريخ تطبيق الخصم أو المكافأة فعلياً على راتب الموظف.",
  cost: "تكلفة الأصناف المباعة أو المشتراة.",
  cost_basis: "تكلفة الوحدة المعتمدة عند احتساب قيمة حركة التسوية.",
  cost_change: "الفرق بين تكلفة الصنف الحالية وتكلفته في بداية فترة المقارنة.",
  cost_of_goods_sold: "تكلفة البضاعة المباعة (الكمية المباعة × تكلفة الوحدة).",
  cost_price: "سعر تكلفة الوحدة من الصنف.",
  created_at: "تاريخ إنشاء السجل.",
  created_by: "اسم المستخدم الذي أنشأ العملية.",
  created_date: "تاريخ إنشاء السجل.",
  credit: "المبلغ الدائن في هذه الحركة (يخفّض المبلغ المستحق على الطرف).",
  current_cost: "تكلفة الوحدة الحالية للصنف.",
  current_margin_percent: "هامش الربح الحالي للصنف بناءً على سعر البيع الحالي مقابل متوسط تكلفته ((سعر البيع - متوسط التكلفة) ÷ سعر البيع × 100).",
  current_wacc: "متوسط التكلفة المرجح الحالي لوحدة الصنف.",
  customer_count: "عدد العملاء المختلفين.",
  customer_id: "معرف العميل.",
  customer_name: "اسم العميل.",
  daily_salary: "قيمة الراتب اليومي للموظف (الراتب الشهري ÷ عدد أيام العمل في الشهر).",
  date: "تاريخ الحركة أو العملية.",
  days_of_stock: "عدد الأيام التي تكفي فيها الكمية الحالية في المخزون بناءً على متوسط معدل البيع اليومي خلال الفترة.",
  days_overdue: "عدد الأيام المنقضية منذ تاريخ استحقاق القسط دون سداد.",
  days_since_last_movement: "عدد الأيام المنقضية منذ آخر حركة مخزون على هذا الصنف.",
  days_since_last_purchase: "عدد الأيام المنقضية منذ آخر عملية شراء.",
  days_since_last_sale: "عدد الأيام المنقضية منذ آخر عملية بيع لهذا الصنف.",
  days_until_expiry: "عدد الأيام المتبقية حتى تاريخ انتهاء صلاحية الصنف.",
  debit: "المبلغ المدين في هذه الحركة (يزيد المبلغ المستحق على الطرف).",
  deduction_type: "كود نوع الخصم.",
  deduction_type_label: "نوع الخصم المطبق على الموظف.",
  description: "بيان أو وصف تفصيلي للحركة.",
  details: "تفاصيل إضافية عن الإجراء المسجل.",
  direction: "كود اتجاه الحركة المالية (داخل أو خارج).",
  direction_label: "اتجاه الحركة المالية: داخلة إلى الخزينة أو خارجة منها.",
  discount: "قيمة الخصم الممنوح على الفاتورة.",
  discount_invoice_count: "عدد الفواتير التي تضمنت خصماً استثنائياً منحه الكاشير.",
  discount_range: "الفئة التي تقع ضمنها نسبة الخصم الممنوح على الفاتورة (مثال: 5-10%).",
  distinct_customers: "عدد العملاء المختلفين الذين تعاملوا مع هذا الصنف.",
  distinct_suppliers: "عدد الموردين المختلفين الذين تم الشراء منهم.",
  doc_no: "رقم المستند.",
  doc_type: "كود نوع المستند.",
  doc_type_label: "نوع المستند الذي نتجت عنه هذه الحركة المالية (فاتورة بيع، تحصيل، مصروف...).",
  down_payment: "قيمة الدفعة المقدمة عند بدء خطة التقسيط.",
  drawer_name: "اسم الساحب المدوّن على الشيك.",
  due_date: "تاريخ استحقاق السداد.",
  employee_id: "معرف الموظف.",
  employee_name: "اسم الموظف.",
  estimated_revenue_impact: "الأثر التقديري لتجاوزات الكاشير في الأسعار على إجمالي الإيراد.",
  exception_type: "نوع الاستثناء أو المخالفة المسجلة على الفاتورة (إلغاء، خصم استثنائي، تجاوز سعر).",
  excludes_from_treasury: "يشير إلى أن حركات هذه الوسيلة لا تُحتسب ضمن رصيد الخزينة.",
  expected_cash: "النقدية المتوقع وجودها في الدرج عند الإغلاق (النقدية الافتتاحية + مبيعات الوردية النقدية).",
  expense_count: "عدد المصروفات المسجلة.",
  expenses: "إجمالي قيمة المصروفات.",
  expiry_date: "تاريخ انتهاء صلاحية الصنف.",
  expiry_status: "حالة صلاحية الصنف (سارية، قاربت على الانتهاء، منتهية).",
  first_invoice_date: "تاريخ أول فاتورة للعميل.",
  first_period_cost: "تكلفة الوحدة المسجلة في بداية فترة المقارنة.",
  first_purchase_date: "تاريخ أول عملية شراء لهذا الصنف.",
  first_sale_date: "تاريخ أول عملية بيع لهذا الصنف.",
  frequency: "دورية سداد أقساط خطة التقسيط (شهري، أسبوعي...).",
  frequency_monthly: "معدل عدد مرات شراء العميل التقديري شهرياً (عدد الفواتير ÷ عدد أيام تعامله × 30).",
  full_name: "الاسم الكامل للمستخدم.",
  fully_paid_count: "عدد الفواتير الآجلة التي تم سدادها بالكامل.",
  gross_profit: "صافي المبيعات بعد خصم المرتجعات ناقص تكلفة البضاعة المباعة.",
  gross_sales: "إجمالي قيمة الفواتير بعد الخصم والإضافات وقبل خصم المرتجعات.",
  handled_by: "اسم المستخدم الذي تولى تنفيذ عملية الإرجاع.",
  hour_slot: "الساعة من اليوم التي حدثت خلالها المبيعات.",
  id: "المعرف الفريد للسجل.",
  input_vat: "ضريبة القيمة المضافة المدفوعة على المشتريات، والتي يمكن خصمها من ضريبة المخرجات المستحقة.",
  installment_amount: "قيمة القسط الواحد المستحق.",
  installment_count: "عدد أقساط خطة التقسيط.",
  inventory_value: "قيمة المخزون الحالي من الصنف بمتوسط تكلفته المرجح (الكمية المتاحة × متوسط التكلفة).",
  invoice_count: "عدد الفواتير.",
  invoice_no: "رقم الفاتورة.",
  is_recurring: "يشير إلى أن هذا الخصم أو المكافأة يتكرر تلقائياً كل دورة راتب.",
  item_code: "كود الصنف.",
  item_count: "عدد الأصناف المختلفة.",
  item_id: "معرف الصنف.",
  item_name: "اسم الصنف.",
  items_per_invoice: "متوسط عدد الأصناف في الفاتورة الواحدة.",
  items_returned: "عدد الأصناف التي شملتها عملية الإرجاع.",
  job_title: "المسمى الوظيفي للموظف.",
  label: "بيان توضيحي للبند.",
  last_cost: "آخر تكلفة شراء مسجّلة لوحدة الصنف.",
  last_due_date: "تاريخ آخر استحقاق مسجّل لأقساط العميل.",
  last_expense_date: "تاريخ آخر مصروف مسجّل في هذه الفئة.",
  last_invoice_date: "تاريخ آخر فاتورة.",
  last_login: "تاريخ ووقت آخر تسجيل دخول للمستخدم.",
  last_movement_at: "تاريخ ووقت آخر حركة مسجّلة على وسيلة الدفع هذه.",
  last_movement_date: "تاريخ آخر حركة مخزون على الصنف.",
  last_period_cost: "تكلفة الوحدة المسجلة في نهاية فترة المقارنة.",
  last_purchase_cost: "آخر تكلفة تم الشراء بها لوحدة الصنف.",
  last_purchase_date: "تاريخ آخر عملية شراء.",
  last_return_date: "تاريخ آخر عملية إرجاع مسجّلة.",
  last_sale_date: "تاريخ آخر عملية بيع للصنف.",
  lifetime_gross_profit: "إجمالي الربح المتحقق من الصنف منذ أول عملية بيع له حتى الآن (كل إيرادات المبيعات ناقص كل التكاليف والمرتجعات).",
  line_total: "إجمالي قيمة سطر الفاتورة (الكمية × سعر الوحدة).",
  low_stock_alerts_count: "عدد الأصناف التي وصل رصيدها إلى حد إعادة الطلب أو أقل.",
  low_stock_items: "عدد الأصناف التي رصيدها في هذا المخزن أقل من الحد الأدنى المحدد لها.",
  margin_decline_percent: "نسبة تراجع هامش ربح الصنف في الفترة الحالية مقارنة بالفترة السابقة.",
  margin_percent: "نسبة مجمل الربح إلى صافي المبيعات (الربح ÷ صافي المبيعات × 100).",
  method_category: "تصنيف وسيلة الدفع (نقدي، إلكتروني...).",
  method_icon: "الأيقونة المعروضة لوسيلة الدفع.",
  method_id: "معرف وسيلة الدفع.",
  method_key: "مفتاح داخلي يُستخدم لتجميع حركات نفس وسيلة الدفع معاً.",
  method_name: "اسم وسيلة الدفع.",
  method_type: "نوع وسيلة الدفع.",
  min_margin_percent: "الحد الأدنى المسموح به لهامش الربح على هذا الصنف.",
  min_stock_qty: "الحد الأدنى للكمية المطلوب توفرها من الصنف قبل التنبيه بإعادة الطلب.",
  movement_type: "نوع حركة المخزون (إدخال، إخراج، تحويل، تسوية...).",
  name: "الاسم.",
  net_amount: "صافي أثر الحركة على الخزينة (المبلغ الداخل ناقص المبلغ الخارج).",
  net_flow: "صافي حركة الحساب البنكي خلال الفترة (إجمالي الإيداعات ناقص إجمالي السحوبات).",
  net_profit: "صافي الربح بعد إضافة الإيرادات الأخرى وخصم كل المصروفات والمسحوبات من مجمل الربح.",
  net_purchases: "إجمالي المشتريات من المورد بعد خصم قيمة المرتجعات.",
  net_quantity_purchased: "صافي الكمية المشتراة من الصنف بعد خصم الكمية المرتجعة.",
  net_salary: "صافي الراتب المستحق للموظف بعد إضافة المكافآت وخصم الاستقطاعات وخصومات السلف.",
  net_sales: "إجمالي الفواتير ناقص قيمة المرتجعات.",
  net_total_cost: "صافي تكلفة الكمية المشتراة بعد خصم تكلفة الكمية المرتجعة.",
  net_vat: "الفرق بين ضريبة المخرجات وضريبة المدخلات، وهو المبلغ المستحق للحكومة أو القابل للاسترداد.",
  notes: "ملاحظات إضافية على السجل.",
  occurred_at: "تاريخ ووقت حدوث حركة التكلفة فعلياً.",
  opened_date: "تاريخ فتح الوردية.",
  opening_cash: "قيمة النقدية الموجودة في الدرج عند فتح الوردية.",
  other_revenues: "إجمالي الإيرادات الأخرى غير الناتجة عن المبيعات.",
  output_vat: "ضريبة القيمة المضافة المحصَّلة على المبيعات والمستحقة للحكومة.",
  outstanding: "المبلغ المتبقي غير المحصَّل من إجمالي المستحق (المستحق ناقص المحصَّل).",
  overdue_amount: "المبلغ المستحق الذي تجاوز عمره 30 يوماً ولم يُسدد بعد.",
  overdue_bucket: "الفئة الزمنية التي تصنّف مدى تأخر سداد القسط.",
  overdue_count: "عدد خطط التقسيط التي بها أقساط متأخرة السداد.",
  overdue_receivables_count: "عدد ذمم العملاء التي تجاوزت موعد استحقاقها.",
  override_count: "عدد المرات التي عدّل فيها الكاشير سعر صنف يدوياً.",
  paid_amount: "المبلغ المدفوع فعلياً.",
  paid_at: "تاريخ سداد القسط أو الدفعة.",
  paid_count: "عدد المدفوعات.",
  partially_paid_count: "عدد الفواتير الآجلة التي سُدد جزء من قيمتها فقط.",
  party: "اسم الطرف المرتبط بالحركة (عميل، مورد، أو جهة عامة).",
  party_id: "معرف الطرف المرتبط بالحركة.",
  party_type: "نوع الطرف المرتبط بالحركة (عميل، مورد، عام).",
  payload_json: "تفاصيل العملية بصيغة تقنية كما سُجّلت في سجل التدقيق.",
  payment_breakdown: "تفصيل المبالغ الموزعة على وسائل الدفع المختلفة عند الدفع بأكثر من وسيلة.",
  payment_method: "وسيلة الدفع المستخدمة.",
  payment_type: "طريقة الدفع المستخدمة في الفاتورة.",
  pct: "نسبة هذا البند إلى إجمالي الإيرادات في قائمة الأرباح والخسائر.",
  pct_of_sales: "نسبة هذا الصف إلى إجمالي المبيعات.",
  pct_of_total: "نسبة هذا البند إلى إجمالي القيمة الكلية.",
  pending_count: "عدد الحالات المعلّقة.",
  percentage: "النسبة المئوية لهذا البند من الإجمالي.",
  period: "الفترة الزمنية التي يمثلها هذا الصف.",
  period_end: "نهاية الفترة الزمنية.",
  period_label: "اسم الفترة الضريبية المشمولة بالإقرار.",
  period_start: "بداية الفترة الزمنية.",
  phone: "رقم هاتف التواصل.",
  plan_count: "عدد خطط التقسيط.",
  potential_profit: "الربح المتوقع تحقيقه عند بيع كامل الكمية المتبقية في المخزون بسعر البيع الحالي، بعد خصم تكلفتها.",
  potential_revenue: "الإيراد المتوقع تحقيقه عند بيع كامل الكمية المتبقية في المخزون بسعر البيع الحالي.",
  previous_margin_percent: "هامش الربح المسجل للصنف في الفترة السابقة قبل حدوث التغير.",
  price_downs: "عدد مرات قيام الكاشير بتخفيض سعر صنف عن سعره الأصلي.",
  price_ups: "عدد مرات قيام الكاشير برفع سعر صنف عن سعره الأصلي.",
  purchase_count: "عدد فواتير الشراء.",
  purchase_date: "تاريخ فاتورة الشراء.",
  purchase_no: "رقم فاتورة الشراء.",
  purchase_price: "سعر شراء الوحدة من الصنف.",
  purchase_qty: "الكمية التي تم شراؤها من الصنف.",
  purchase_return_qty: "الكمية المرتجعة من مشتريات الصنف.",
  purchase_return_value: "قيمة الكمية المرتجعة من مشتريات الصنف.",
  purchase_value: "إجمالي قيمة الكمية المشتراة من الصنف.",
  purchases_total: "إجمالي قيمة المشتريات.",
  qty_change: "مقدار التغير في كمية الصنف نتيجة التسوية (بالزيادة أو النقصان).",
  quantity: "الكمية.",
  quantity_purchased: "الكمية المشتراة من الصنف.",
  quantity_returned: "الكمية المرتجعة.",
  quantity_sold: "الكمية المباعة من الصنف.",
  raw_method: "كود وسيلة الدفع كما ورد في المستند الأصلي قبل مطابقته بوسائل الدفع المعرّفة في النظام.",
  reason: "سبب العملية أو الإرجاع.",
  recurring_label: "يوضح ما إذا كان هذا الخصم أو المكافأة يتكرر تلقائياً كل دورة راتب.",
  ref_id: "رقم المستند المصدر لهذه الحركة.",
  reference: "المرجع المرتبط بحركة البنك.",
  reference_id: "رقم المستند المرجعي لهذه الحركة.",
  reference_no: "رقم مرجعي للحركة.",
  reference_type: "نوع المستند المرجعي لهذه الحركة.",
  refund_method: "الطريقة التي استُرد بها المبلغ للعميل.",
  remaining: "المبلغ المتبقي غير المسدد.",
  remaining_balance: "الرصيد المتبقي من السلفة بعد خصم الدفعات المسددة.",
  remaining_pct: "نسبة المبلغ المتبقي غير المسدد إلى الإجمالي.",
  repaid_amount: "المبلغ الذي تم سداده من السلفة حتى الآن.",
  repeat_items: "عدد الأصناف التي تم شراؤها من هذا المورد أكثر من مرة، وتُستخدم لقياس تذبذب أسعاره.",
  resource: "الشاشة أو المورد الذي طاله الإجراء المسجل.",
  return_amount: "قيمة المبلغ المرتجع.",
  return_count: "عدد عمليات الإرجاع.",
  return_discount: "قيمة الخصم المخصوم من مبلغ المرتجع.",
  return_increase: "قيمة الإضافات المضافة على مبلغ المرتجع.",
  return_rate_percent: "نسبة قيمة المرتجعات إلى إجمالي المشتريات من هذا المورد (المرتجعات ÷ المشتريات × 100).",
  return_ref: "الرقم المرجعي لعملية الإرجاع.",
  return_total: "صافي قيمة المرتجع بعد الخصم والإضافة.",
  returns_amount: "إجمالي قيمة المرتجعات.",
  returns_cost: "تكلفة الأصناف التي تم إرجاعها.",
  returns_count: "عدد عمليات الإرجاع.",
  returns_handled: "عدد عمليات الإرجاع التي تعامل معها الكاشير.",
  returns_total: "إجمالي قيمة المرتجعات.",
  revenue: "قيمة الإيراد المتحقق من المبيعات.",
  revenue_count: "عدد الإيرادات المسجلة.",
  role: "صلاحية المستخدم في النظام.",
  running_balance: "الرصيد التراكمي للحساب بعد كل حركة بالترتيب الزمني.",
  running_quantity: "الكمية التراكمية للصنف بعد كل حركة تكلفة بالترتيب الزمني.",
  running_total: "الرصيد التراكمي لوسيلة الدفع بعد تسجيل كل حركة.",
  running_wacc: "متوسط التكلفة المرجح للوحدة محسوباً تراكمياً بعد كل حركة تكلفة على الصنف.",
  salary: "الراتب المحدد للموظف.",
  salary_period: "دورية صرف الراتب (شهري، أسبوعي...).",
  sale_price: "سعر بيع الوحدة من الصنف.",
  sales_cost: "تكلفة الأصناف المباعة من هذا الصنف خلال دورة حياته.",
  sales_qty: "الكمية المباعة من الصنف.",
  sales_return_qty: "الكمية المرتجعة من مبيعات الصنف.",
  sales_return_value: "قيمة الكمية المرتجعة من مبيعات الصنف.",
  sales_revenue: "إجمالي إيراد مبيعات الصنف.",
  sales_total: "إجمالي قيمة المبيعات.",
  section: "القسم الذي ينتمي إليه هذا البند في التقرير.",
  selling_total: "مجموع أسعار البيع قبل الخصومات والإضافات.",
  settled_at: "تاريخ صرف الراتب للموظف.",
  settled_by: "اسم المستخدم الذي قام بصرف الراتب.",
  shift_count: "عدد الورديات.",
  shift_id: "رقم الوردية.",
  signed_amount: "قيمة الحركة موقّعة بإشارة: سالبة إذا كانت خارجة من الخزينة، وموجبة إذا كانت داخلة إليها.",
  source: "مصدر الرصيد (خزينة أو بنك).",
  source_doc_no: "رقم المستند الأصلي الذي نتجت عنه حركة التكلفة.",
  source_group: "التصنيف العام لمصدر الحركة المالية (مبيعات، مشتريات، مصروفات...).",
  source_id: "معرف المستند المصدر لحركة التكلفة.",
  source_line_id: "معرف سطر المستند المصدر لحركة التكلفة.",
  source_table: "اسم الجدول الذي نتجت عنه حركة التكلفة.",
  spread_min_max: "الفرق بين أعلى وأقل تقييم لقيمة المخزون المتبقي من الصنف بين طرق التكلفة الأربع (متوسط التكلفة، الوارد أولاً، الوارد أخيراً، آخر سعر شراء).",
  status: "الحالة الحالية للمستند أو العملية.",
  status_label: "الحالة الحالية للعملية أو خطة التقسيط (نشطة، مسددة، متأخرة...).",
  stock_on_hand: "الكمية المتوفرة حالياً من الصنف في المخزون.",
  stock_quantity: "الكمية المتوفرة من الصنف في المخزون.",
  stock_status: "حالة رصيد الصنف (متوفر، منخفض، نافد).",
  stock_velocity_status: "تصنيف حركة الصنف بناءً على عدد الأيام التي يكفيها المخزون الحالي: نافد، راكد (بلا مبيعات)، مخزون زائد، مخزون ناقص، أو سليم.",
  sub_type: "تصنيف فرعي لنوع الحركة المالية المسجلة للموظف.",
  subtotal: "إجمالي الفاتورة قبل خصم الخصم.",
  suggested_price: "سعر البيع المقترح لتحقيق الحد الأدنى لهامش الربح المحدد لهذا الصنف.",
  supplier_count: "عدد الموردين.",
  supplier_id: "معرف المورد.",
  supplier_name: "اسم المورد.",
  system_quantity: "الكمية المسجلة في النظام لحظة إعداد كشف الجرد، قبل مقارنتها بالعدّ الفعلي.",
  tax_rate: "نسبة الضريبة المطبقة.",
  tax_type_label: "طريقة احتساب الضريبة على الفاتورة (مضافة على السعر أو شاملة داخل السعر).",
  taxable_amount: "قيمة المشتريات الخاضعة لضريبة القيمة المضافة.",
  taxable_sales: "قيمة المبيعات الخاضعة لضريبة القيمة المضافة.",
  total: "إجمالي قيمة المستند.",
  total_amount: "إجمالي قيمة المبلغ.",
  total_billed: "إجمالي المبلغ المستحق على العميل خلال الفترة.",
  total_bonuses: "إجمالي قيمة المكافآت المضافة لراتب الموظف.",
  total_cost: "إجمالي تكلفة الأصناف.",
  total_deductions: "إجمالي قيمة الخصومات المطبقة على راتب الموظف.",
  total_deposits: "إجمالي قيمة الإيداعات في الحساب البنكي.",
  total_discount: "إجمالي قيمة الخصومات الممنوحة.",
  total_due: "إجمالي الرصيد المستحق على الطرف من كل الفواتير غير المسددة إضافة إلى الرصيد الافتتاحي.",
  total_expenses: "إجمالي قيمة المصروفات.",
  total_header_discount: "إجمالي قيمة الخصم المطبق على مستوى الفاتورة نفسها (بخلاف خصومات الأصناف).",
  total_in: "إجمالي المبالغ الداخلة.",
  total_items_sold: "إجمالي عدد قطع الأصناف المباعة.",
  total_out: "إجمالي المبالغ الخارجة.",
  total_paid: "إجمالي المبلغ المدفوع.",
  total_purchases: "إجمالي قيمة المشتريات.",
  total_quantity: "إجمالي الكمية.",
  total_remaining: "إجمالي المبلغ المتبقي غير المسدد.",
  total_returns: "إجمالي قيمة المرتجعات.",
  total_revenues: "إجمالي قيمة الإيرادات.",
  total_sales: "إجمالي قيمة المبيعات.",
  total_transactions: "إجمالي عدد المعاملات.",
  total_value: "إجمالي قيمة المخزون من الصنف (الكمية × تكلفة الوحدة).",
  total_withdrawals: "إجمالي قيمة المسحوبات.",
  transaction_count: "عدد المعاملات.",
  transfer_in_qty: "الكمية الواردة للصنف عبر التحويلات بين المخازن.",
  transfer_out_qty: "الكمية الصادرة من الصنف عبر التحويلات بين المخازن.",
  turnover_ratio: "معدل دوران المخزون خلال الفترة (تكلفة البضاعة المباعة ÷ قيمة المخزون)، ويوضح عدد مرات تدوير قيمة المخزون.",
  tx_count: "عدد الحركات.",
  tx_type_label: "نوع الحركة المالية المسجلة للموظف (خصم، مكافأة، سلفة، صرف راتب...).",
  type: "نوع الحركة أو المستند.",
  unit_cost: "تكلفة الوحدة.",
  unit_name: "اسم وحدة قياس الصنف.",
  unit_price: "سعر بيع الوحدة.",
  updated_at: "تاريخ آخر تعديل على السجل.",
  user_id: "معرف المستخدم.",
  username: "اسم المستخدم لتسجيل الدخول.",
  value_fifo: "قيمة المخزون المتبقي بطريقة الوارد أولاً يُصرف أولاً، أي تقييم الكمية المتبقية بتكلفة أحدث الدفعات الواردة.",
  value_impact: "الأثر المالي لحركة التسوية على قيمة المخزون (الفرق في الكمية × تكلفة الوحدة).",
  value_last: "قيمة المخزون المتبقي محسوبة بآخر سعر شراء مسجّل للصنف.",
  value_lifo: "قيمة المخزون المتبقي بطريقة الوارد أخيراً يُصرف أولاً، أي تقييم الكمية المتبقية بتكلفة أقدم الدفعات الواردة.",
  value_share_pct: "نسبة قيمة مخزون هذا المخزن إلى إجمالي قيمة المخزون في كل المخازن.",
  value_wacc: "قيمة المخزون المتبقي محسوبة بمتوسط التكلفة المرجح للوحدة.",
  vat_amount: "قيمة ضريبة القيمة المضافة.",
  vat_reversed: "قيمة الضريبة المستردة نتيجة إرجاع الفاتورة.",
  wacc: "متوسط تكلفة الشراء المرجح للوحدة حسب الكميات الواردة.",
  warehouse_id: "معرف المخزن.",
  warehouse_name: "اسم المخزن.",
  weekday_name: "اسم يوم الأسبوع.",
  weekday_num: "الرقم التسلسلي ليوم الأسبوع.",
  withdrawals: "إجمالي قيمة المسحوبات من الخزينة.",
  working_days_per_month: "عدد أيام العمل المعتمدة شهرياً لاحتساب الراتب اليومي للموظف.",
};

// Column order per report. Re-synced to the actual SQL output keys of each query
// (introspected against the live schema). Lists every column the query returns so the
// order is deterministic; technical join/grouping keys (customer_id, item_id, …) are
// placed last and hidden by default via INTERNAL_KEYS.
const REPORT_COLUMN_KEYS = {
  // ── Sales ──
  "daily-sales": ["date", "invoice_count", "selling_total", "total_discount", "additions_amount", "gross_sales", "total_cost", "returns_amount", "returns_count", "net_sales", "gross_profit", "avg_invoice_value", "margin_percent"],
  "detailed-sales": ["invoice_no", "date", "customer_name", "cashier", "payment_type", "status", "subtotal", "discount", "additions_amount", "total", "item_count", "payment_breakdown", "customer_id"],
  "sales-by-item": ["item_code", "item_name", "category_name", "quantity_sold", "revenue", "total_discount", "cost", "returns_amount", "returns_cost", "gross_profit", "margin_percent", "avg_unit_price", "selling_total", "avg_unit_cost", "wacc"],
  "sales-by-category": ["category_name", "item_count", "quantity_sold", "revenue", "total_discount", "cost", "returns_amount", "returns_cost", "gross_profit", "margin_percent", "selling_total", "avg_unit_cost"],
  "sales-by-cashier": ["cashier", "invoice_count", "cancelled_count", "total_sales", "total_discount", "avg_invoice_value", "total_items_sold", "total_cost", "returns_handled", "returns_cost", "net_sales", "gross_profit", "margin_percent", "items_per_invoice"],
  "sales-by-payment": ["payment_type", "invoice_count", "total_sales", "total_discount", "returns_amount", "avg_transaction", "net_sales", "pct_of_sales"],
  "sales-heatmap": ["weekday_name", "hour_slot", "invoice_count", "total_sales", "avg_sale", "weekday_num", "customer_id"],
  "exceptions": ["invoice_no", "date", "customer_name", "exception_type", "discount", "status", "total"],
  "period-comparison": ["period", "date", "invoice_count", "total_sales", "total_discount", "returns_amount", "net_sales", "total_cost", "gross_profit", "margin_percent", "avg_invoice_value"],
  "gross-net-sales": ["date", "invoice_count", "selling_total", "total_discount", "additions_amount", "gross_sales", "total_cost", "returns_amount", "net_sales", "gross_profit", "avg_invoice_value", "margin_percent"],
  "sales-returns": ["return_ref", "invoice_no", "date", "customer_name", "handled_by", "return_discount", "return_increase", "return_total", "reason", "refund_method", "items_returned", "id", "customer_id"],
  "discount-analysis": ["section", "payment_type", "discount_range", "invoice_count", "total_discount", "avg_discount", "avg_discount_percent", "total_sales"],
  "margin-by-item": ["item_code", "item_name", "category_name", "quantity_sold", "revenue", "cost", "returns_amount", "gross_profit", "margin_percent", "selling_total", "avg_unit_price", "avg_unit_cost", "wacc"],
  "margin-by-category": ["category_name", "quantity_sold", "revenue", "cost", "returns_amount", "gross_profit", "margin_percent", "selling_total", "avg_unit_cost"],
  "margin-health": ["item_name", "wacc", "sale_price", "current_margin_percent", "min_margin_percent", "suggested_price", "below_threshold", "item_id"],
  "shift-history": ["id", "cashier", "opened_date", "closed_at", "opening_cash", "closing_cash", "sales_total", "expected_cash", "cash_variance", "invoice_count", "status"],

  // ── Purchases ──
  "purchase-summary": ["date", "purchase_count", "distinct_suppliers", "total_discount", "additions_amount", "total_purchases", "avg_order_value"],
  "detailed-purchases": ["purchase_no", "date", "supplier_name", "total", "total_discount", "additions_amount", "status", "payment_type", "item_count", "created_by", "id", "supplier_id"],
  "purchases-by-supplier": ["supplier_name", "purchase_count", "total_purchases", "avg_order_value", "returns_total", "net_purchases", "last_purchase_date"],
  "purchases-by-item": ["item_code", "item_name", "quantity_purchased", "total_cost", "quantity_returned", "returns_cost", "net_quantity_purchased", "net_total_cost", "avg_unit_cost", "distinct_suppliers", "last_purchase_date"],
  "purchase-returns": ["return_ref", "supplier_name", "date", "return_discount", "return_increase", "return_total", "reason", "refund_method", "items_returned", "id"],
  "supplier-pricing": ["supplier_name", "item_name", "unit_price", "quantity", "line_total", "purchase_date"],

  // ── Inventory ──
  "slow-moving": ["item_code", "item_name", "category_name", "stock_quantity", "cost_price", "total_value", "potential_revenue", "potential_profit", "last_sale_date"],
  "stock-levels": ["item_code", "item_name", "category_name", "warehouse_name", "quantity", "min_stock_qty", "unit_name", "total_value", "stock_status", "wacc", "last_purchase_cost", "sale_price", "potential_revenue", "warehouse_id"],
  "stock-movements": ["item_code", "item_name", "warehouse_name", "movement_type", "reference_type", "reference_id", "before_qty", "after_qty", "quantity", "created_by", "date", "warehouse_id"],
  "stock-valuation": ["item_code", "name", "category_name", "warehouse_name", "total_quantity", "wacc", "last_purchase_cost", "purchase_price", "total_value", "sale_price", "potential_revenue", "item_id", "warehouse_id"],
  "count-sheet": ["item_code", "item_name", "barcode", "category_name", "warehouse_name", "system_quantity", "unit_name", "warehouse_id"],
  "reorder": ["item_code", "name", "quantity", "min_stock_qty", "unit_name", "id"],
  "expiry": ["batch_no", "item_code", "item_name", "quantity", "expiry_date", "cost_price", "days_until_expiry", "expiry_status"],
  "inventory-aging": ["item_code", "item_name", "quantity", "wacc", "total_value", "last_movement_date", "days_since_last_movement", "aging_bucket"],
  "dead-stock": ["item_code", "item_name", "category_name", "quantity", "wacc", "total_value", "last_sale_date", "days_since_last_sale", "aging_bucket"],
  "cost-movements": ["date", "item_code", "item_name", "warehouse_name", "movement_type", "quantity", "unit_cost", "running_quantity", "running_wacc", "created_by", "source_doc_no", "source_table", "id", "item_id", "source_id", "source_line_id", "occurred_at", "created_at"],
  "cost-method-comparison": ["item_code", "item_name", "category_name", "quantity", "wacc", "last_cost", "value_wacc", "value_fifo", "value_lifo", "value_last", "spread_min_max", "item_id"],
  "item-lifecycle": ["item_code", "item_name", "category_name", "stock_on_hand", "current_wacc", "sale_price", "current_margin_percent", "purchase_qty", "purchase_value", "sales_qty", "sales_revenue", "sales_cost", "sales_return_value", "purchase_return_value", "lifetime_gross_profit", "total_transactions", "distinct_suppliers", "first_purchase_date", "last_purchase_date", "distinct_customers", "first_sale_date", "last_sale_date", "sales_return_qty", "purchase_return_qty", "transfer_in_qty", "transfer_out_qty", "item_id"],
  "margin-drift": ["item_code", "item_name", "category_name", "sale_price", "first_period_cost", "last_period_cost", "current_cost", "cost_change", "previous_margin_percent", "current_margin_percent", "margin_decline_percent", "item_id"],
  "inventory-turnover": ["item_code", "item_name", "category_name", "stock_on_hand", "inventory_value", "quantity_sold", "cogs", "avg_daily_sales", "days_of_stock", "turnover_ratio", "stock_velocity_status", "item_id"],
  "stock-adjustment-audit": ["date", "item_code", "item_name", "category_name", "warehouse_name", "qty_change", "before_qty", "after_qty", "cost_basis", "value_impact", "reason", "created_by", "id"],

  // ── Accounts ──
  "profit-loss": ["section", "label", "amount", "pct"],
  "customer-statement": ["date", "description", "debit", "credit", "running_balance", "item_name", "quantity", "unit_price", "line_total", "item_code"],
  "supplier-statement": ["date", "description", "debit", "credit", "running_balance", "item_name", "quantity", "unit_price", "line_total", "item_code"],
  "daily-owner-snapshot": ["period_start", "period_end", "invoice_count", "selling_total", "total_discount", "additions_amount", "gross_sales", "returns_amount", "net_sales", "cogs", "gross_profit", "expenses", "other_revenues", "withdrawals", "net_profit", "overdue_receivables_count", "low_stock_alerts_count"],

  // ── Treasury ──
  "cash-flow": ["date", "type", "total"],
  "treasury": ["name", "code", "balance", "source", "tx_count"],
  "cash-consistency": ["date", "shift_id", "cashier", "opening_cash", "closing_cash", "sales_total", "expected_cash", "cash_variance", "invoice_count", "status"],
  "payment-method-flow": ["payment_type", "date", "transaction_count", "total_amount", "running_total"],
  "payment-flow-summary": ["method_name", "transaction_count", "total_in", "total_out", "net_amount", "last_movement_at", "method_category", "method_type", "excludes_from_treasury", "method_id", "method_icon"],
  "payment-flow-ledger": ["created_at", "doc_no", "doc_type_label", "direction_label", "amount", "total_in", "total_out", "net_amount", "method_name", "party", "description", "source_group", "party_type", "raw_method", "method_category", "method_type", "doc_type", "direction", "signed_amount", "id", "method_id", "method_icon", "method_key"],
  "payment-flow-by-doc-type": ["doc_type_label", "transaction_count", "total_in", "total_out", "net_amount", "last_movement_at", "doc_type"],
  "payment-flow-by-direction": ["direction_label", "transaction_count", "total_amount", "total_in", "total_out", "net_amount", "last_movement_at", "direction"],
  "payment-flow-running": ["created_at", "method_name", "doc_no", "doc_type_label", "direction_label", "amount", "net_amount", "running_total", "party", "description", "source_group", "party_type", "doc_type", "direction", "raw_method", "id", "method_id", "method_icon", "method_key"],
  "bank-cash-split": ["type", "name", "balance", "percentage"],
  "reconciliation-exceptions": ["date", "shift_id", "cashier", "opening_cash", "closing_cash", "sales_total", "expected_cash", "cash_variance", "invoice_count", "status"],
  "daily-sessions": ["date", "cashier", "opening_cash", "closing_cash", "sales_total", "total_discount", "invoice_count", "cash_variance", "status"],
  "withdrawals-report": ["reference_no", "date", "amount", "reason", "payment_method", "created_by", "id"],

  // ── Tax ──
  "vat": ["tax_rate", "tax_type_label", "taxable_sales", "vat_amount", "invoice_count", "customer_count"],
  "output-vat": ["tax_rate", "tax_type_label", "taxable_amount", "vat_amount", "invoice_count", "customer_count"],
  "input-vat": ["tax_rate", "tax_type_label", "taxable_amount", "vat_amount", "purchase_count", "supplier_count"],
  "vat-filing-summary": ["period_label", "basis_label", "sales_total", "output_vat", "purchases_total", "input_vat", "net_vat"],
  "returns-tax-effect": ["return_ref", "date", "return_amount", "tax_type_label", "vat_reversed", "items_returned", "customer_id", "status_label"],

  // ── Audit / Users ──
  "audit-log": ["id", "full_name", "action", "resource", "payload_json", "created_at", "user_id"],
  "user-activity": ["full_name", "action", "resource", "action_count", "date", "user_id"],
  "user-list": ["id", "username", "full_name", "role", "status", "created_at", "last_login", "updated_at"],
  "user-performance": ["full_name", "invoice_count", "total_sales", "total_discount", "avg_invoice_value", "returns_handled", "returns_amount", "shift_count", "user_id"],
  "login-history": ["full_name", "action", "date", "details", "resource", "id", "user_id"],

  // ── Sales / Purchase returns summaries ──
  "sales-returns-summary": ["date", "return_count", "returns_total", "customer_count", "items_returned", "avg_return_value"],
  "sales-returns-by-customer": ["customer_name", "return_count", "returns_total", "avg_return_value", "last_return_date"],
  "purchase-returns-summary": ["date", "return_count", "returns_total", "supplier_count", "items_returned"],
  "purchase-returns-by-supplier": ["supplier_name", "return_count", "returns_total", "last_return_date"],

  // ── Expenses / Revenues ──
  "expense-summary": ["date", "expense_count", "total_expenses", "avg_expense", "category_count"],
  "detailed-expenses": ["date", "category_name", "amount", "payment_method", "description", "notes", "employee_id"],
  "expenses-by-category": ["category_name", "expense_count", "total_expenses", "avg_expense", "pct_of_total", "last_expense_date"],
  "expenses-by-payment": ["payment_method", "expense_count", "total_expenses", "avg_expense"],
  "revenue-summary": ["date", "revenue_count", "total_revenues", "avg_revenue", "category_count"],
  "detailed-revenues": ["date", "category_name", "amount", "payment_type", "description", "notes"],
  "revenues-by-category": ["category_name", "revenue_count", "total_revenues", "avg_revenue", "pct_of_total"],
  "revenues-by-payment": ["payment_method", "revenue_count", "total_revenues", "avg_revenue"],

  // ── Cheques / Banks ──
  "cheque-listing": ["cheque_no", "bank_name", "type", "amount", "due_date", "status", "drawer_name", "created_date", "notes", "id", "party_type", "party_id"],
  "bank-transactions": ["date", "bank_name", "type", "amount", "reference", "notes", "id"],
  "bank-summary": ["name", "balance", "transaction_count", "total_deposits", "total_withdrawals", "net_flow"],

  // ── Installments ──
  "installment-plans": ["id", "customer_name", "total", "paid_amount", "remaining", "down_payment", "frequency", "installment_count", "installment_amount", "due_date", "status_label", "remaining_pct", "created_date", "paid_at"],
  "installment-collections": ["id", "customer_name", "installment_amount", "method_name", "due_date", "paid_at", "status_label", "remaining", "total"],
  "installments-by-customer": ["customer_name", "plan_count", "total_amount", "total_paid", "total_remaining", "last_due_date", "paid_count", "pending_count", "overdue_count"],
  "installment-delinquent": ["id", "customer_name", "total", "remaining", "installment_amount", "due_date", "days_overdue", "overdue_bucket"],

  // ── Warehouses ──
  "branch-transfers": ["reference_no", "date", "type", "warehouse_name", "item_count", "notes", "created_by", "id"],
  "warehouse-levels": ["warehouse_name", "item_count", "total_quantity", "total_value", "low_stock_items", "value_share_pct"],
  "warehouse-levels-summary": ["warehouse_name", "item_count", "total_quantity", "total_value", "low_stock_items", "value_share_pct"],

  // ── Profit ──
  "profit-by-category": ["category_name", "quantity_sold", "selling_total", "revenue", "cost", "returns_amount", "gross_profit", "margin_percent", "avg_unit_price", "avg_unit_cost"],
  "profit-by-customer": ["customer_name", "invoice_count", "selling_total", "total_discount", "additions_amount", "revenue", "cost", "returns_amount", "gross_profit", "margin_percent", "avg_invoice_value"],
  "profit-by-period": ["date", "invoice_count", "selling_total", "total_discount", "additions_amount", "revenue", "cost_of_goods_sold", "returns_amount", "gross_profit", "expenses", "net_profit", "margin_percent", "avg_invoice_value"],

  // ── Sales analytics ──
  "cashier-override-impact": ["cashier", "override_count", "price_downs", "price_ups", "estimated_revenue_impact", "avg_diff_pct", "discount_invoice_count", "total_header_discount", "avg_discount_pct", "cashier_id"],

  // ── Customer Reports ──
  "ar-aging": ["customer_name", "total_due", "aging_0_30", "aging_31_60", "aging_61_90", "aging_90_plus", "overdue_amount", "last_invoice_date", "phone", "invoice_count"],
  "top-customers": ["customer_name", "total_sales", "net_sales", "gross_profit", "margin_percent", "avg_invoice_value", "invoice_count", "last_invoice_date", "phone", "returns_total", "total_cost"],
  "collection-efficiency": ["customer_name", "total_billed", "collected", "collection_rate", "outstanding", "invoice_count", "partially_paid_count", "fully_paid_count"],
  "customer-loyalty": ["customer_name", "total_sales", "invoice_count", "avg_invoice_value", "frequency_monthly", "items_per_invoice", "avg_discount_percent", "returns_total", "last_invoice_date", "phone", "first_invoice_date", "days_since_last_purchase"],
  "customer-balance-list": ["customer_name", "phone", "balance", "balance_label"],

  // ── Supplier Reports ──
  "ap-aging": ["supplier_name", "total_due", "aging_0_30", "aging_31_60", "aging_61_90", "aging_90_plus", "overdue_amount", "last_purchase_date", "phone", "purchase_count"],
  "supplier-reliability": ["supplier_name", "total_purchases", "purchase_count", "return_rate_percent", "avg_payment_days", "avg_price_spread_percent", "total_returns", "return_count", "last_purchase_date", "phone", "repeat_items"],
  "supplier-balance-list": ["supplier_name", "phone", "balance", "balance_label"],

  // ── Employee Reports ──
  "employee-list": ["employee_name", "job_title", "salary", "salary_period", "working_days_per_month", "daily_salary", "active_deductions_total", "active_bonuses_total", "active_advances_balance", "total_paid", "status", "created_at"],
  "employee-deductions": ["date", "employee_name", "deduction_type_label", "amount", "status", "recurring_label", "completed_at", "cancelled_at", "notes", "created_by", "id", "created_at", "deduction_type", "is_recurring"],
  "employee-bonuses": ["date", "employee_name", "bonus_type_label", "amount", "status", "recurring_label", "completed_at", "cancelled_at", "notes", "created_by", "id", "created_at", "bonus_type", "is_recurring"],
  "employee-advances": ["date", "employee_name", "amount", "remaining_balance", "repaid_amount", "installment_count", "installment_amount", "status", "notes", "created_by", "id", "created_at"],
  "employee-payroll": ["date", "employee_name", "base_salary", "total_bonuses", "total_deductions", "advance_deductions", "net_salary", "period_start", "period_end", "payment_method", "settled_by", "description", "id", "settled_at"],
  "employee-full-history": ["date", "employee_name", "tx_type_label", "amount", "status", "description", "ref_id", "sub_type", "employee_id"],
  "employee-adjustments": ["date", "employee_name", "adjustment_type", "amount", "reason", "created_by", "id"],
};

// Extra analytics columns per report: shipped with the data and toggleable from the
// "الأعمدة" picker, but hidden by default so the default layout stays focused.
const REPORT_EXTRA_KEYS = {
  "daily-sales": new Set(["avg_invoice_value", "margin_percent"]),
  "gross-net-sales": new Set(["avg_invoice_value", "margin_percent"]),
  "sales-by-item": new Set(["selling_total", "avg_unit_cost", "wacc"]),
  "margin-by-item": new Set(["selling_total", "avg_unit_price", "avg_unit_cost", "wacc"]),
  "sales-by-category": new Set(["selling_total", "avg_unit_cost"]),
  "margin-by-category": new Set(["selling_total", "avg_unit_cost"]),
  "sales-by-cashier": new Set(["margin_percent", "items_per_invoice"]),
  "sales-by-payment": new Set(["net_sales", "pct_of_sales"]),
  "period-comparison": new Set(["margin_percent", "avg_invoice_value"]),
  "sales-returns-summary": new Set(["avg_return_value"]),
  "sales-returns-by-customer": new Set(["avg_return_value"]),
  "purchases-by-supplier": new Set(["net_purchases"]),
  "stock-levels": new Set(["wacc", "last_purchase_cost", "sale_price", "potential_revenue"]),
  "stock-valuation": new Set(["sale_price", "potential_revenue"]),
  "slow-moving": new Set(["potential_profit"]),
  "warehouse-levels": new Set(["value_share_pct"]),
  "warehouse-levels-summary": new Set(["value_share_pct"]),
  "vat-filing-summary": new Set([]),
  "expenses-by-category": new Set(["pct_of_total"]),
  "revenues-by-category": new Set(["pct_of_total"]),
  "bank-summary": new Set(["net_flow"]),
  "payment-flow-summary": new Set(["method_category", "method_type", "excludes_from_treasury", "method_id", "method_icon"]),
  "payment-flow-ledger": new Set(["source_group", "party_type", "raw_method", "method_category", "method_type", "doc_type", "direction", "signed_amount", "id", "method_id", "method_icon", "method_key"]),
  "payment-flow-by-doc-type": new Set(["doc_type"]),
  "payment-flow-by-direction": new Set(["direction"]),
  "payment-flow-running": new Set(["source_group", "party_type", "doc_type", "direction", "raw_method", "id", "method_id", "method_icon", "method_key"]),
  "customer-statement": new Set(["amount", "item_code", "barcode"]),
  "supplier-statement": new Set(["amount", "item_code", "barcode"]),
  "profit-by-customer": new Set(["avg_invoice_value"]),
  "profit-by-period": new Set(["margin_percent", "avg_invoice_value"]),
  "profit-by-category": new Set(["avg_unit_price", "avg_unit_cost"]),
  "ar-aging": new Set(["phone", "invoice_count"]),
  "ap-aging": new Set(["phone", "purchase_count"]),
  "top-customers": new Set(["phone", "returns_total", "total_cost"]),
  "collection-efficiency": new Set(["partially_paid_count", "fully_paid_count"]),
  "supplier-reliability": new Set(["phone", "repeat_items"]),
  "customer-loyalty": new Set(["phone", "first_invoice_date", "days_since_last_purchase"]),
  "customer-balance-list": new Set([]),
  "supplier-balance-list": new Set([]),

  // ── Employee Reports ──
  "employee-list": new Set(["working_days_per_month", "daily_salary", "active_deductions_total", "active_bonuses_total", "active_advances_balance", "total_paid", "created_at"]),
  "employee-deductions": new Set(["recurring_label", "completed_at", "cancelled_at", "notes", "created_by", "id", "created_at", "deduction_type", "is_recurring"]),
  "employee-bonuses": new Set(["recurring_label", "completed_at", "cancelled_at", "notes", "created_by", "id", "created_at", "bonus_type", "is_recurring"]),
  "employee-advances": new Set(["repaid_amount", "installment_count", "installment_amount", "notes", "created_by", "id", "created_at"]),
  "employee-payroll": new Set(["payment_method", "settled_by", "description", "id", "settled_at"]),
  "employee-full-history": new Set(["description", "ref_id", "sub_type", "employee_id"]),
  "employee-adjustments": new Set(["reason", "created_by", "id"]),
  "shift-history": new Set(["id"]),
  "user-activity": new Set(["user_id"]),
};

const CODE_KEYS = new Set(["id", "item_code", "code", "sku", "barcode", "invoice_no", "purchase_no", "ref_no", "return_ref", "reference_id", "shift_id", "user_id", "warehouse_id", "batch_no", "section"]);
const DATE_KEYS = new Set(["date", "created_at", "opened_date", "closed_at", "purchase_date", "last_purchase_date", "last_invoice_date", "last_sale_date", "last_movement_date", "expiry_date", "updated_at"]);
const PERCENT_KEYS = new Set(["pct", "margin_percent", "current_margin_percent", "min_margin_percent", "avg_discount_percent", "collection_rate", "percentage", "tax_rate", "avg_discount_percent", "collection_rate", "pct_of_sales", "pct_of_total", "value_share_pct"]);
const NUMBER_KEYS = new Set(["quantity", "quantity_sold", "quantity_purchased", "stock_quantity", "system_quantity", "total_quantity", "before_qty", "after_qty", "min_stock_qty", "item_count", "invoice_count", "purchase_count", "returns_count", "return_count", "items_returned", "transaction_count", "action_count", "total_invoices", "total_items_sold", "distinct_suppliers", "supplier_count", "customer_count", "tx_count", "days_until_expiry", "days_since_last_movement", "days_since_last_sale", "days_to_collect", "weekday_num", "cancelled_count", "loyalty_points", "suggested_order_qty", "returns_handled", "weekday_num", "shift_count", "items_per_invoice"]);

// Money keys that lack an obvious substring match below (e.g. WACC).
const MONEY_KEYS = new Set(["wacc", "current_wacc", "running_wacc", "net_purchases", "selling_total", "net_flow"]);

function inferType(key) {
  if (CODE_KEYS.has(key)) return "code";
  if (DATE_KEYS.has(key) || key.endsWith("_date")) return "date";
  if (PERCENT_KEYS.has(key) || key.endsWith("_percent")) return "percent";
  if (NUMBER_KEYS.has(key) || key.endsWith("_count")) return "number";
  if (MONEY_KEYS.has(key)) return "money";
  if (key.includes("price") || key.includes("cost") || key.includes("total") || key.includes("amount") || key.includes("balance") || key.includes("sales") || key.includes("profit") || key.includes("discount") || key.includes("increase") || key.includes("vat") || key.includes("cash") || key.includes("revenue") || key.includes("value") || key.includes("collected") || key.includes("outstanding") || key.includes("due")) return "money";
  return "text";
}

function inferPriority(key, index) {
  if (INTERNAL_KEYS.has(key)) return "optional";
  if (index < 5) return "essential";
  if (index < 9) return "useful";
  return "optional";
}

// Technical/internal columns: kept available (toggleable) but hidden by default
// so reports don't surface raw plumbing (JSON blobs, source-table names, helper ids).
const INTERNAL_KEYS = new Set([
  "payload_json", "source_table", "source_doc_no", "weekday_num", "party_type",
  "party_id", "reference_id", "reference_type", "plan_id",
  // Join/grouping keys that duplicate a human-readable column already shown
  // (e.g. customer_id alongside customer_name). Kept available but hidden by default.
  "customer_id", "supplier_id", "cashier_id", "item_id", "warehouse_id", "user_id",
  "employee_id", "source_id", "source_line_id",
]);

function labelForKey(key) {
  return AR_LABELS[key] || key;
}

// ── Totals-row aggregation ─────────────────────────────────────────────
// Summing every numeric column produces nonsense for ratios (margin % totals to
// 450%), averages, unit prices and running balances. Each totals cell is either:
// a plain sum (additive), recomputed from summed parts (ratio), or omitted
// (non-additive → the UI renders a dash).
//
// A ratio rule's num/den are candidate expressions tried in order; an expression
// is a list of column keys where a "-key" term subtracts. The first expression
// whose keys all exist in the rows wins.
const TOTALS_RATIO_RULES = {
  margin_percent:    { num: [["gross_profit"]], den: [["net_sales"], ["revenue", "-returns_amount"], ["total_sales", "-returns_amount"], ["revenue"]], percent: true },
  collection_rate:   { num: [["collected"]], den: [["total_billed"]], percent: true },
  remaining_pct:     { num: [["remaining"]], den: [["total"]], percent: true },
  avg_invoice_value: { num: [["total_sales"], ["gross_sales"], ["selling_total"], ["total"]], den: [["invoice_count"]] },
  avg_transaction:   { num: [["total_sales"]], den: [["invoice_count"], ["transaction_count"]] },
  avg_sale:          { num: [["total_sales"]], den: [["invoice_count"]] },
  avg_order_value:   { num: [["total_purchases"]], den: [["purchase_count"]] },
  avg_return_value:  { num: [["returns_total"]], den: [["return_count"]] },
  avg_expense:       { num: [["total_expenses"]], den: [["expense_count"]] },
  avg_revenue:       { num: [["total_revenues"]], den: [["revenue_count"]] },
  avg_unit_price:    { num: [["selling_total"], ["revenue"]], den: [["quantity_sold"]] },
  avg_unit_cost:     { num: [["cost"], ["total_cost"], ["net_total_cost"]], den: [["quantity_sold"], ["net_quantity_purchased"], ["quantity_purchased"]] },
  avg_discount:      { num: [["total_discount"]], den: [["invoice_count"]] },
  items_per_invoice: { num: [["total_items_sold"]], den: [["invoice_count"]] },
};

// Percent columns that ARE additive because they are shares of one whole.
const TOTALS_ADDITIVE_PERCENTS = new Set(["pct_of_sales", "pct_of_total", "percentage", "value_share_pct"]);

// Keys whose sum is meaningless — totals cell omitted entirely.
const TOTALS_SKIP_KEYS = new Set([
  "wacc", "current_wacc", "running_wacc", "unit_price", "unit_cost", "cost_price",
  "sale_price", "purchase_price", "last_purchase_cost", "last_cost", "avg_cost",
  "suggested_price", "installment_amount", "salary", "daily_salary", "base_salary",
  "opening_balance", "closing_balance", "opening_cash", "closing_cash", "expected_cash",
  "tax_rate", "turnover_ratio", "frequency_monthly", "avg_daily_sales", "days_of_stock",
  "shift_id", "weekday_num", "hour_slot", "before_qty", "after_qty", "spread_min_max",
  "min_stock_qty", "min_stock", "working_days_per_month", "installment_no", "plan_id",
  "cost_change", "current_cost", "first_period_cost", "last_period_cost",
]);

function totalsModeForKey(key, type) {
  if (TOTALS_RATIO_RULES[key]) return "ratio";
  if (TOTALS_SKIP_KEYS.has(key)) return "skip";
  if (
    key.startsWith("avg_") || key.startsWith("running_") || key.startsWith("days_") ||
    key.startsWith("min_") || key.startsWith("max_") || key.endsWith("_days")
  ) return "skip";
  if (type === "percent") return TOTALS_ADDITIVE_PERCENTS.has(key) ? "sum" : "skip";
  if (type === "money" || type === "number") return "sum";
  return "skip";
}

function sumColumn(rows, key) {
  let sum = 0;
  let seen = false;
  for (const row of rows) {
    const raw = row?.[key];
    if (raw == null || raw === "") continue;
    const val = Number(raw);
    if (!isNaN(val)) { sum += val; seen = true; }
  }
  return seen ? sum : null;
}

function evalTotalsExpr(rows, candidates) {
  for (const expr of candidates) {
    let total = 0;
    let ok = true;
    for (const term of expr) {
      const negate = term.startsWith("-");
      const s = sumColumn(rows, negate ? term.slice(1) : term);
      if (s == null) { ok = false; break; }
      total += negate ? -s : s;
    }
    if (ok) return total;
  }
  return null;
}

function computeReportTotals(rows, columns) {
  const totals = {};
  if (!rows?.length || !columns?.length) return totals;
  columns.forEach((col) => {
    const mode = totalsModeForKey(col.key, col.type);
    if (mode === "skip") return;
    if (mode === "ratio") {
      const rule = TOTALS_RATIO_RULES[col.key];
      const num = evalTotalsExpr(rows, rule.num);
      const den = evalTotalsExpr(rows, rule.den);
      if (num == null || den == null || den === 0) return;
      const value = rule.percent ? (num / den) * 100 : num / den;
      totals[col.key] = Math.round(value * 100) / 100;
      return;
    }
    const sum = sumColumn(rows, col.key);
    if (sum != null) totals[col.key] = Math.round(sum * 100) / 100;
  });
  return totals;
}

// How many *core* (non-extra, non-internal) columns are visible by default.
const MAX_DEFAULT_VISIBLE = 12;

function buildColumn(key, coreIndex = 0, hidden = false) {
  return {
    key,
    label: labelForKey(key),
    desc: COLUMN_DESCRIPTIONS[key] || "",
    type: inferType(key),
    printPriority: hidden ? "optional" : inferPriority(key, coreIndex),
    // Hidden (extra/internal) columns never take a visible slot, so appending extras
    // can't bump a core column (e.g. gross_profit) out of the default view.
    defaultVisible: !hidden && coreIndex < MAX_DEFAULT_VISIBLE,
  };
}

function orderKeys(keys, slug) {
  const preferred = REPORT_COLUMN_KEYS[slug] || [];
  const used = new Set();
  const ordered = [];
  preferred.forEach((key) => {
    if (keys.includes(key) && !used.has(key)) {
      ordered.push(key);
      used.add(key);
    }
  });
  keys.forEach((key) => {
    if (!used.has(key)) ordered.push(key);
  });
  return ordered;
}

function getReportColumns(slug, rows = []) {
  const rowKeys = Object.keys(rows?.[0] || {});
  const catalogKeys = REPORT_COLUMN_KEYS[slug] || [];
  const keys = rowKeys.length ? orderKeys(rowKeys, slug).filter(k => !k.startsWith('_')) : catalogKeys;
  const extras = REPORT_EXTRA_KEYS[slug];
  let coreIndex = 0;
  return keys.map((key) => {
    const hidden = INTERNAL_KEYS.has(key) || (extras ? extras.has(key) : false);
    return buildColumn(key, hidden ? Infinity : coreIndex++, hidden);
  });
}

function getReportTitle(slug, fallback = "") {
  return REPORT_TITLES[slug] || fallback || slug;
}

function getReportDescription(slug) {
  return REPORT_DESCRIPTIONS[slug] || "";
}

function normalizeStructuredReport(data) {
  if (!data || typeof data !== "object" || Array.isArray(data)) return null;
  if (Array.isArray(data.rows)) {
    return {
      rows: data.rows,
      sections: Array.isArray(data.sections) ? data.sections : [],
      summary: data.summary || null,
    };
  }
  if (Array.isArray(data.transactions)) {
    const summary = { ...data };
    delete summary.transactions;
    return { rows: data.transactions, sections: [], summary };
  }
  const sections = [];
  ["by_payment", "by_range"].forEach((key) => {
    if (Array.isArray(data[key])) {
      const sectionLabel = key === "by_payment" ? "حسب طريقة الدفع" : "حسب نطاق الخصم";
      sections.push({ key, label: sectionLabel, rows: data[key] });
    }
  });
  if (sections.length) {
    const rows = sections.flatMap((section) => section.rows.map((row) => ({ section: section.label, ...row })));
    return { rows, sections, summary: null };
  }
  return null;
}

// ── Cell-value translations ────────────────────────────────────────────
// Maps raw English string values returned by SQL queries to their Arabic
// equivalents so the client can display translated cell data.
const VALUE_TRANSLATIONS = {
  // ── Invoice / document status ──
  paid: "مدفوع",
  unpaid: "غير مدفوع",
  partial: "جزئي",
  cancelled: "ملغي",
  voided: "ملغى",
  active: "نشط",
  pending: "معلق",
  open: "مفتوح",
  closed: "مغلق",
  overdue: "متأخر",
  settled: "مسدد",
  completed: "مكتمل",
  returned: "مرتجع بالكامل",
  partially_returned: "مرتجع جزئي",

  // ── Cheque status ──
  cleared: "محصل",
  bounced: "مرتد",
  replaced: "مستبدل",

  // ── Purchase order / quotation status ──
  approved: "موافق عليه",
  draft: "مسودة",
  sent: "مرسل",

  // ── Payment type / method ──
  cash: "نقدي",
  credit: "آجل",
  card: "بطاقة",
  wallet: "محفظة",
  bank_transfer: "تحويل بنكي",
  multi: "متعدد",
  installments: "تقسيط",
  future_due: "آجل مستحق",

  // ── Direction ──
  in: "وارد",
  out: "صادر",

  // ── Source (treasury) ──
  treasury: "خزينة",
  bank: "بنك",

  // ── Stock velocity status ──
  overstocked: "مخزون زائد",
  understocked: "مخزون ناقص",
  healthy: "سليم",

  // ── Document types (payment flow) ──
  pos_invoice: "فاتورة كاش",
  credit_invoice: "فاتورة آجلة",
  installment_invoice: "فاتورة تقسيط",
  payment_allocation: "تسوية دفع",
  customer_payment: "دفعة عميل",
  supplier_payment: "دفعة مورد",
  ajal_payment: "دفعة آجل",
  expense: "مصروف",
  revenue: "إيراد",
  purchase: "شراء",
  purchase_payment: "دفعة شراء",
  withdrawal: "سحب",
  sales_return: "مرتجع مبيعات",
  purchase_return: "مرتجع شراء",

  // ── Account statement types ──
  invoice: "فاتورة مبيعات",
  payment: "دفعة",
  adjustment: "تسوية",

  // ── Bank transaction types ──
  deposit: "إيداع",

  // ── Stock movement types ──
  branch_receive: "استلام فرع",
  opening_balance: "رصيد افتتاحي",
  manual_adjustment: "تسوية يدوية",
  transfer: "تحويل",

  // ── Refund / settlement methods ──
  cash_back: "استرداد نقدي",
  split: "تقسيط",
  account: "على الحساب",

  // ── User roles ──
  admin: "مدير النظام",
  cashier: "كاشير",
  manager: "مشرف",

  // ── Party types ──
  customer: "عميل",
  supplier: "مورد",
  general: "عام",

  // ── Employee transaction types ──
  deduction: "خصم",
  bonus: "مكافأة",
  advance: "سلفة",
  advance_payment: "دفعة سلفة",
  settlement: "صرف راتب",

  // ── Period comparison ──
  period_1: "الفترة الأولى",
  period_2: "الفترة الثانية",

  // ── Discount ranges ──
  "0-5%": "0-5%",
  "5-10%": "5-10%",
  "10-20%": "10-20%",
  "20%+": "20%+",

  // ── Tax type ──
  exclusive: "مضافة خارج السعر",
  inclusive: "شاملة داخل السعر",

  // ── Fallback / prefix strings ──
  unknown: "غير معروف",
  other: "أخرى",
};

module.exports = {
  REPORT_COLUMN_KEYS,
  REPORT_TITLES,
  REPORT_DESCRIPTIONS,
  COLUMN_DESCRIPTIONS,
  VALUE_TRANSLATIONS,
  labelForKey,
  getReportColumns,
  getReportTitle,
  getReportDescription,
  normalizeStructuredReport,
  computeReportTotals,
};
